### ISSUE TITLE
Protect from Accidental Deletion

### ISSUE THREAD

**Issue by isaiahh1013** [cannatag/ldap3#1003]
Hi! I’m trying to create a new Organizational Unit with LDAP3. However, One of the requirements is to enable “Protect from Accidental Deletion”. Any suggestions? Thank you!

**Comment by zorn96** [comment]
hi @isaiahh1013 ! I'm going to assume you're dealing with active directory.
permissions aren't an inherent part of the ldap protocol, and protecting an object from accidental deletion is simply setting a DENY ACE for the "delete" and "delete subtree" permissions on the OU object. in AD, permissions can be returned and modified via a specially encoded `ntSecurityDescriptor` parameter, that comes across as bytes

since this is AD-specific, and not actually part of the protocol, `ldap3` doesn't have utilities for it.
however, there are other AD-specific libraries that build on `ldap3` and do have utilities for this sort of thing. one such library is `ms_active_directory` which can be found here: https://github.com/zorn96/ms_active_directory/

it has utilities for getting the security descriptor on an object in a parsed, manageable way, and has functions for updating the descriptor to modify the permissions, and defines constants for common permissions, which you can use to accomplish your goal

**Comment by isaiahh1013** [comment]
Thank you so much @zorn96! I do see in the documents that it mentions being able to add permissions to the security descriptor, however I don’t see anywhere in the docs how to do it. Is there any examples I can go off of on how to achieve this?

**Comment by zorn96** [comment]
hi @isaiahh1013 we can continue this thread on the issue you opened for the other library

**Comment by isaiahh1013** [comment]
Thank you @zorn96! I opened issue #39 over there.
