### ISSUE TITLE
Can't connect TLS

### ISSUE THREAD

**Issue by ggandgmaak** [cannatag/ldap3#1011]
Hello! I tried to start TLS connection with self-signed cert., but i get error "('unable to open socket', [(LDAPSocketOpenError("('socket ssl wrapping error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)',)"), ('adress', 636))])". How can i add my certs to trusted for lib or get with this error somehow?
Thank you!

**Comment by ofl-tkn-manager** [comment]
hi @ggandgmaak !
you can set the TLS settings to use the `ssl` library's verify none option. TLS settings are documented here:
https://ldap3.readthedocs.io/en/latest/ssltls.html

alternatively you could use the options mentioned in that documentation to specifically trust only the self-signed cert. that might not be a great practice though, since self-signed certs offer very little in way of security

**Comment by iskylite** [comment]
How did you solve this problem

**Comment by no0neCare** [comment]
> How did you solve this problem

Hello! In my case, coz i work in closed network i just used validate = ssl.CERT_NONE. But it is dangerously unsafe.
