### ISSUE TITLE
Mock LDAP server for testing?

### ISSUE THREAD

**Issue by midnightlynx** [cannatag/ldap3#115]
Projects using `python-ldap` or `pyldap` for their LDAP connection can use the `mockldap` package in unit testing, so as not to make any changes in real LDAP server data.

Do you know if `mockldap` is compatible with `ldap3`-based unit testing, and if not, do you know if any projects of that sort exist that are?

**Comment by cannatag** [comment]
Hi, I've been working on the MockSync and MockAsync strategies inside ldap3 for a while, but I didn't go much farther because I had not real need for them. If  you are interested I can try to keep working on them. My idea was to emulate an ldap server with default responses. Do you have any suggestion on how these strategies should work? 

Bye,
Giovanni

-------- Messaggio originale --------
Da:midnightlynx <notifications@github.com>
Inviato:Tue, 13 Oct 2015 01:37:52 +0200
A:cannatag/ldap3 <ldap3@noreply.github.com>
Oggetto:[ldap3] Mock LDAP server for testing? (#115)

**Comment by midnightlynx** [comment]
The general approach in `mockldap` is for the developer to provide an initial mock LDAP directory in dictionary form that queries are run against. Reading queries return the appropriate data from the dictionary, writing queries remove or modify what's in the dictionary, etc.
The mock LDAP object internally records which method calls are made, with which arguments, and provides a method to inspect this record.
They haven't fully implemented mocking of all query operations against the mock dictionary, so they also provide a way to seed methods so that a particular given set of args and kwargs will return a particular seeded result.
The way they implemented the recording and seeding can be here, and is independent of their particular implementation of the LDAP interaction:
https://bitbucket.org/psagers/mockldap/src/b6b3fba5345e04b511b947c2184c501d37a5156c/src/mockldap/recording.py

So... Maybe something like that?

**Comment by cannatag** [comment]
My idea with MockSync and MockAsync is to describe in a json file what a specific operation is expected to return, so this is similar to the recording/seeding option in mockldap. I also started a project to build a pure python ldap 3 server bit this is still very rudimentary. Once it becomes more functional it could bé used forse mocking too. If you're interested I could tra to speed up its development.

**Comment by midnightlynx** [comment]
Please see what you can do, if it's not too much trouble. I could find use for them.

**Comment by cornelinux** [comment]
Hi I created my own simple ldap3mock:
https://github.com/privacyidea/privacyidea/blob/master/tests/ldap3mock.py

which I am using here
https://github.com/privacyidea/privacyidea/blob/master/tests/test_lib_resolver.py#L419

**Comment by roxanagherle** [comment]
Hi,

I've been playing with a mockSync strategy, you can find my first attempt here: https://github.com/roxanagherle/ldap3/blob/master/ldap3/strategy/mockSync.py
It's very similar to the mockldap library just adapted to ldap3.
I would like to use a mockSync strategy for some openstack unit tests code, so I would like to improve the code and get it in ldap3. Would love to hear your feedback/suggestions.

**Comment by cannatag** [comment]
Hi Roxana,
thanks for yor coding! I've got a fast look at your code and it looks very good. I have some questions: 
I've seen that you rewrote the filter parser in filter.py. Why don't you use the parse in the ldap3 library? Also I've seen you import the "ldap" package in filter.py. Do you mean the python-ldap package? I'd like not to include it in the ldap3 library because it compiles from the openldap client libraries and is not compatible with python3.

My original idea with mocking was to create a simple python ldap3 server (via the ldap3.core.server.Server.from_definition() method that create a fake server with a predefined schema) and include it in the mock strategies. The mock server should emulate a real server and should be dynamically loaded with mock data. 

I started the sldap3 project but it is still in a very pre-alpha stage, also because I choose to use the new asyncio module of the python library but it's still not stable. Furthermore the ldap3 library is python2/python3 compatible and the asyncio is only for python3 so I used a compatiility module (trololio) that is not updated since November 2014.

Can you describe what you would like to have in the mock strategy? I could change my former idea of building a real ldap3 python server and work on somihing simpler, starting from your code.

Thanks again for the time you spent on the ldap3 library.
Giovanni

**Comment by roxanagherle** [comment]
Hi Giovanni,
thanks for your reply! and thanks for the awesome ldap3 library.
I was looking at the sldap3 project and even though it seems a cool idea to have have a ldap3 python server to simulate the responses it also looked like it was too complex for what we needed and not sure if we wanted to introduce too many variable dependencies like the ones you were talking about. It might be a great idea, but we wanted to have something faster.

Basically I would like to have a mock strategy that can simulate responses for simple ldap operations starting from a user provided initial set of data, I am sure we can't support all search filters or modify combinations but at least cover the basic operations and then enhance it as needed.

Good point on the filter parser, we don't want to have python-ldap as a dependency, I might have not noticed it has that import. I didn't find any code in ldap3 that can be used to filter a set of data based on the search filter, so let me know if that exists in ldap3 since it would be of great help.

Thanks!
Roxana

**Comment by cannatag** [comment]
Hi Roxana, thanks for your kind words and for the remarks on the sldap3 project. Your point is right, to havea whole server is quite complex and is also against the tdd principle of isolation of unit testing, so your approach is better. I'll try to work on your code in the weekend to simulate the bind and the search operations. If the approach is correct then we can work on the other ldap operations. I'd prefer to have a way to "load" the directory key/values pairs from an external source (as a json file) so that the python files don't need to be modified when working with the mock strategy.

Bye,
Giovanni

**Comment by roxanagherle** [comment]
Hi Giovanni,

Great! Thanks for your quick response and availability to help on this. Much appreciated!
An external source for the initial mock data set would be great, I don't think I have any strong opinion if that's a json file or anything else. I didn't see a way to pass the mock data to the strategy so I'm curious to see how we can 'load' the data from the external source.

Thanks again,
Roxana

**Comment by cannatag** [comment]
please look at mocksync.py code in dev. I've included all ldap operations except search. You can define mock identities (for simple bind) and entries at run time with connection.strategy.add_user() connection.strategy.remove_user(), connection.strategy.add_entry(), connection.strategy.remove_entry() or load them from a json file with connection.strategy.users_from_json(), connection.strategy.entries_from_json().  The json entry file can be automatically generated by a real server with connection.response_to_json(raw=True, checked_attributes=False) atfer you searched the entries.

You can also define a dummy server with complete and real info and schema with the offline schema defined in ldap3. There are two ways of doing that:

```
server_2 = Server('dummy', get_info=OFFLINE_SLAPD_2_4)
```
or
```
    schema = SchemaInfo.from_json(edir_8_8_8_schema)
    info = DsaInfo.from_json(edir_8_8_8_dsa_info, schema)
    server_1 = Server.from_definition('MockSyncServer', info, schema)
```

with the former you use a predefined schema already present in ldap3, with the latter you can load any schema previously saved from a real server (in this case I'm using the json representation of edirectory already present in ldap3). 

Look at the file testMockStrategy.py in the test folder for a complete configuration example.

I'll work on the mock_search() operation in the next days. Let me know what you think of this code.

Bye,
Giovanni

**Comment by roxanagherle** [comment]
Hi Giovanni,

This is awesome work! I really like how the code looks and also nice idea on introducing the schema server validation for attributes. One question that I have around that is how easy will it be to use connection.strategy.add_entry() in tests, do I just have to ensure that my mock attributes are supported by the schema? Ideally, I would like it to be as easy as possible for a developer to create a mock entry and not have to create that data each time by running this on a real ldap server. I'm gonna play with this today.

Also, do you think that users data could be part of the big entries dictionary as well, or did you choose to separate the users data for simplicity on the binding code?

Looking forward to play with this more.
Nice stuff!

Thanks,
Roxana

**Comment by cannatag** [comment]
HI,
the schema server validation is optional, if you don't specify any schema no validation is done.

I divided the users data from the entries dictionary because with other authentication mechanisms different from Simple bind the users are not required to be defined in the DIT (Directory Information Tree). But in this case I think the mock strategy  will only have Simple binds so I could include them in the entries dictionary, To be used as an account the "userPassword" must be present and its value should be a clear text password (or more than one, as specified by the RFCs).

Have fun,
Giovanni

**Comment by cannatag** [comment]
I've added tests for the server without schema (connection_3 and server_3 in testMockSyncStrategy.py).

**Comment by roxanagherle** [comment]
Thanks for the clarifications around schema validation.
Agreed for including the users in the entries dictionary. that will reduce complexity.

Let me know if I can help in any way with the search mocking. I think that could be more complex because of the variety of search filters.

Thanks,
Roxana

**Comment by cannatag** [comment]
I was thinking to change the self.entries dictionary to a tree structure (similar to the parsed filter. This would help in serching, but increase the complexity of the code. I'm applying to this strategy some ideas I had for the sldap3 project, so I would eventually reuse this code in that project. 

What do you think?

**Comment by roxanagherle** [comment]
hi Giovanni,

I see that in the recent code you added you still use dictionary for self.entries and the filter evaluation looks very good at a first glimpse. I'm gonna read through that code today. If we can pull it off at least for the most common search filters and not having to introduce tree structure it would be great and easier to use (in my opinion).

Thanks!
Roxana

**Comment by cannatag** [comment]
The filter parser is almost complete. It miss the substring portion. I hope to complete it in the weekend. I modified the strategy to store the attributes values in bytes because that's how the client portion of the ldap3 receives the data.

Let me know if it works.

Bye,
Giovanni

**Comment by cannatag** [comment]
I added the substring matching, but have still not thoroughly tested it. 
The search should be complete, only the "approximate" and "extensible" evaluation are missing. But I've never used them. The rfc states that if approximate is not supported it should be treated as an equality match. The "extensible" requires also that matchingRules are defined on the server side, and this is not the case with the MockStrategy.

Please do some test and let me know what is wrong.

**Comment by cannatag** [comment]
MockSync successfully tested against 2.6, 2.7 .3.3, 3.4, 3.5.

**Comment by roxanagherle** [comment]
Played today with testing the mock_search and everything worked perfectly.

I don't think we use  "approximate" and "extensible" filters either, so I wouldn't be too worried of those.
I'm gonna start using this in our unit test code.

Thanks again for your quick help on this. This looks awesome!
Roxana

**Comment by cannatag** [comment]
Refactored MockSyncStrategy to allow creation of MockAsyncStrategy, now there is a a MockBaseStrategy to inherit from. Fixed result value for mock_search. Now returns success even if no entries is found. noSuchObject is returned only when the base is incorrect as specified by RFCs.

**Comment by cannatag** [comment]
mockSyncStrategy complete. Added docs. Will be released in 1.3.0

**Comment by JohnTheodore** [comment]
I just wrote a few ldap3 mock tests using what was talked about on this thread, and it just works (love it when that happens). I appreciate everyone on this thread working on this!

**Comment by cannatag** [comment]
Thanks, just to let you know that in the upcoming 2.2.5 version also the MockAsyncStrategy is fully functional.
