### ISSUE TITLE
[Q] to hash the ldap-pw

### ISSUE THREAD

**Issue by colttt** [cannatag/ldap3#144]
Hello,

can you tell me please if ldap3 support hash-password? If so, how can i use them?
```
import ldap3
LDAP_HOST = 'ipa.demo1.freeipa.org'
LDAP_PORT = 636
LDAP_USE_SSL = 'true'
LDAP_USER = 'uid=Administrator,cn=ipa,dc=demo1,dc=freeipa,dc=de'
LDAPW_PW = 'hElLo!?'
BINDDN = 'cn=groups,cn=ipa,dc=demo1,dc=freeipa,dc=de'

server = ldap3.Server(LDAP_HOST, port = LDAP_PORT, use_ssl = LDAP_USE_SSL)
conn = ldap3.Connection(server, user=LDAP_USER, password=LDAPW_PW, auto_bind=True)
```
thanks in advance!

**Comment by cannatag** [comment]
Hi Colttt,
Hashing password is supported. Please have a look at http://ldap3.readthedocs.org/standard.html. Let me know if you need additional help.

Bye,
Giovanni

**Comment by colttt** [comment]
Hi Cannatag,

thanks for you response, but so far i can see it is only to modify a password, but i will hash 'LDAPW_PW' so that nobody see the password in the script.

**Comment by cannatag** [comment]
You can try with:

```
>>> from ldap3 import HASHED_SALTED_SHA
>>> from ldap3.utils.hashed import hashed

>>> hashed_password = hashed(HASHED_SALTED_SHA, 'new_password')
```
and then store the hashed password in your program. But I'm not sure if you can use it for bind(). because the RFC states that the simple password must be in cleartext.

By the way if security is an issue you should use a different autentication method. You should see what SASL mechanisms are available in your server and try to use one that doens't require a password (as a certificate).

**Comment by colttt** [comment]
ok so far i can see its not possible, so i close this comment
