### ISSUE TITLE
bindRequests in pooled connections are always successful

### ISSUE THREAD

**Issue by roxanagherle** [cannatag/ldap3#165]
When using pooled connections with ReusableStrategy the bind requests always return success, even if you try to authenticate with wrong password.

This code https://github.com/cannatag/ldap3/blob/master/ldap3/strategy/reusable.py#L388 seems to return always a successful bind.  Is there any reason for that?

**Comment by cannatag** [comment]
Hi,
that's a fake request. The actual bind() operation is performed in any of the worker connection when there is an actual operation to perform, look at line 231.

The connection are "lazy" so they open and bind only when there is some work to do. You should get the unsuccessful bind message once you try to perform an actual operation. bind(), unbind() and start_tls() are trapped and executed only when the worker has some work to do.

Bye,
Giovanni

**Comment by morganfainberg** [comment]
It would be nice to have a "validation" bind attempt rather than having to wait until sometime down the line when work is being performed (and generating an error at that point during runtime). Overall the cost of a bind attempt is pretty low on "initialization" of the pool and might be worth adding.

**Comment by cannatag** [comment]
Good point. Will work on this.

Giovanni

**Comment by roxanagherle** [comment]
A 'validation' bind attempt would be really nice to have.
Thanks for the quick answers!

**Comment by cannatag** [comment]
Please check code in dev. The reusable strategy now  performs a test bind on a single worker connection when the bind() operation is issued.
I've also refined the strategy, abandon() operation are not honored because thay should be executed by the same thread. Also the only useful function of the abandon() operation is a sort of "ping" when issuing an abandon(0) operation to reset the server timeout session. But this is not defined in any rfc. Instead abandon(0) should be illegal because the client should abandon only current operations. So I don't think that this is a limitation for the Reusable strategy.

**Comment by roxanagherle** [comment]
Hi Giovanni,

Code looks great, thank you!
I just tested the validation bind and it works perfectly - gives an error when I give it wrong credentials.
I don't have any strong opinions on the abandon request, so I'm good with that.

Thanks,
Roxana

**Comment by cannatag** [comment]
good. the fix will be included in the next release of ldap3. Abandon is almost a no-op nowadays because server are so fast and operation are executed almost immediately..

**Comment by cannatag** [comment]
fixed in 1.3.0. validates also NTLM and SASL bindings
