### ISSUE TITLE
attribute argument in search() should accept any iterable

### ISSUE THREAD

**Issue by klada** [cannatag/ldap3#177]
`Connection.search()` supports a list of attributes to be specified to limit the amount of attributes in the result set.

However it does not support the `dict_keys` type, which means that the following code works in Python2, but not in Python3:

```python
conn.search(base, filter, attributes=any_dict.keys())
```
This is because `dict.keys()` returns a list in Python2. This could be fixed by either adding the `dict_keys` type to `SEQUENCE_TYPES` or by checking if the argument passed to `search()` as `attributes` is iterable.

Of course this could also be fixed in the code using `ldap3`, but from what I have seen so far it is quite common to pass in dictionary keys as an attribute limiter for LDAP queries. And nevertheless with this issue `ldap3` is behaving differently on different Python versions.

**Comment by cannatag** [comment]
Thanks. The easiest solution is to add dict.keys to SEQUENCE_TYPES. I will check if this has drawbacks on the existing codebase and will include it in the next release of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
Hi,
can you try to change the SEQUENCE_TYPES assignment in the __init__.py file with:
```
SEQUENCE_TYPES = (list, tuple, GeneratorType, type(dict().keys()))
```

and tell me if this is working as expected? I didn't find a direct reference to the class type of dict_keys class.

Thanks,
Giovanni

**Comment by klada** [comment]
Hi,

the fix you have provided is working. Thanks for the quick reply.

After thinking about this for a bit I came up with a different solution, which does not involve checking the  `SEQUENCE_TYPES` constant. In my opinion a more sustainable solution could be to check whether `attributes` is iterable or not. I have prepared a PR for this (PR #178). Of course it is up to you which solution you'll prefer :)

**Comment by cannatag** [comment]
I tought the same, but then I realized that I use the SEQUENCE_TYPES in many lines of code.So adding the type of the dict_keys let you use the dict_keys anywhere in the library where SEQUENCE_TYPES is used. The problem with checking if a variable is an iterable (that can be done with isinstance(collections.Iterable too) is that strings are sequences, but I must exclude them from sequence types else you get the weird ['h', 'e', 'l', 'l', 'o'] output. I see that you properly excluded this in your check. I think I should substitute the SEQUENCE_TYPES with a function that include your "if condition" and use it instead of the SEQUENCE_TYPES condition through the whole library.

I will try to do this in the next release.

Thanks for your suggestion,
Giovanni
