### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by hughrobb** [cannatag/ldap3#182]
What would it take to add direct asyncio support for python 3.5?

I like your underlying implementation and interface quite well, but I'd like to mix it in to an already asyncio-heavy project without blocking or threads.  I stumbled across Bonsai, but its not nearly so complete or self-contained.

I'm thinking I should subclass BaseStrategy and add an async def'd Connection.  Am I on the right track or am I missing something important?

**Comment by cannatag** [comment]
Hi, I started to work on a asyncio ldap3 server project (sldap3 on github) using ldap3 but I stopped when I found that it was not possible to wrap a plain socket in a ssl socket in the main loop. I created an issue on the python bug tracking  site (https://bugs.python.org/issue23749). Wrapping a socket with sleep is needed for the start_tls operation. 

Anyway I think you should subclass the SyncStrategy connection and yield from the send and receive methods, but I'm quite new to async programming, so I'm not sure if this is the correct approach.

Anyway I would be happy to help and include a new strategy in the ldap3 library.

Bye,
Giovanni

**Comment by hughrobb** [comment]
Giovanni,
Thanks for the response.  Glad I'm not too far off base.  Thanks for the warning about the start_tls issue.  Would you object to a python 3.5+ solution?  Honestly, asyncio prior to 3.5 isn't worth any attention.
I'd be delighted to take a swing at it.  And that'd be grand if my work can get incorporated.  I'll get back to you when I have a proof-of-concept implementation.
Best,Hugh

 

    On Friday, June 3, 2016 12:53 PM, Giovanni Cannata <notifications@github.com> wrote:
 

 Hi, I started to work on a asyncio ldap3 server project (sldap3 on github) using ldap3 but I stopped when I found that it was not possible to wrap a plain socket in a ssl socket in the main loop. I created an issue on the python bug tracking site (https://bugs.python.org/issue23749). Wrapping a socket with sleep is needed for the start_tls operation. Anyway I think you should subclass the SyncStrategy connection and yield from the send and receive methods, but I'm quite new to async programming, so I'm not sure if this is the correct approach.Anyway I would be happy to help and include a new strategy in the ldap3 library.Bye,
Giovanni—

**Comment by hughrobb** [comment]
I've got two versions working, but both need some tidying up.
1. AsyncioStrategy(SyncStrategy)
  thunks to asyncio event loop behind the scenes - so it blocks only (but also always) where it's called from.  no api changes.  i did refactor a couple of internal methods in the strategy classes to save myself some typing.
2. aioldap.LDAPClient & aioldap.LDAPServer
  transport, c = await loop.create_connection(LDAPClient, '123.123.123.123', 389)
  await c.bind(...)
  async for result in c.search(...): pass
  await c.starttls()
  async for result in c.search(...): pass
  c.close()
  await c.wait_closed()
  
In both cases, messages are passed through the asyncio event loop - and all of bind, search & starttls work correctly.

I'm not terribly happy with #1.  It's all upside down and requires an extra layer of wrapping to make it play nicely if you really want to treat the methods as asynchronous.

#2 is Transport-Protocol based and it'd be pretty easy to add a synchronous layer to it that'd allow users to ignore asyncio running under the hood.  And both the LDAPClient & LDAPServer classes derive from a LDAPProtocol that fuses together a lot of the commonalities between the two -- if you are still keen on providing ldap server functionality (something I need as well).  Also, being transport agnostic should make building tests a breeze by letting a pipe be placed between ldapclient & ldapserver in the same process.

Thanks by the way for the excellent comments and well-factored code.  It made writing the aioldap stuff a pleasure.

**Comment by hughrobb** [comment]
I'll put my code in a little scratch repository on github in the next couple of days.  Understand, it's just proof-of-concept so many arguments are hard-coded and there are lots of elisions. 

    On Monday, June 6, 2016 2:08 AM, Giovanni Cannata <notifications@github.com> wrote:
 

 Very impressive work! I'm curious about both versions. The first seems to better fit in the ldap3 strategies mechanism while the second is more suitable for async programming. Do you have some code to show?Thanks again for your support.—

**Comment by hughrobb** [comment]
Take a look and let me know what you think: https://github.com/hughrobb/aioldap3

**Comment by cannatag** [comment]
Hi, I took a look at your code, but I don't see how this can be integrated into ldap3. It uses a different asn1 library (ldap3 uses pyasn1 for sending and a custom faster asn1 decoder for received messages) and messages are built in a different way. I will play with it to understand how it works.

**Comment by hughrobb** [comment]
It is a prototype, a proof-of-concept.  It is not intended to be directly integrated, although I think that is a conversation worth having as the world certainly would be better with one complete ldap library rather than multiple reimplementations.
As for asn1crypto, again, let me remind you this is a proof-of-concept.  I spent twenty minutes working on adding the missing message types to ldap3's encoding/decoding system and still didn't have it working.  Which for a prototype was much too long - the whole of this library took me 2 straight hours from start to finish.  So I flipped over to an admittedly imperfect asn.1 library, but doing so meant only 10 minutes of time from pip install to working server & client.
In large, I agree a custom DER encoding is the right choice.  pyasn1 is unpleasant and bog-slow.  And even if it were wonderful, a generic encoding/decoding library is an inappropriate burden for LDAP message exchange.
The only interesting places in the code are protocol.py, server.py & client.py.  I think most of your interest might be in the two starttls() methods.  SSLProtocol is part of the asyncio API - and it does all the real work.
Now what I did that's not completely above-board, is directly rerouting the linkage between the transport and protocol.  However, those parts of the transport and protocol code in asyncio are pretty stable.  And there are on-going discussions to provide a supported API for "wrapping sockets" - though the abstractions used really mean manipulating a stack of transport-protocol pairings.  And hopefully this'll happen in a version or two. 

    On Thursday, June 9, 2016 2:27 AM, Giovanni Cannata <notifications@github.com> wrote:
 

 Hi, I took a look at your code, but I don't see how this can be integrated into ldap3. It uses a different asn1 library (ldap3 uses pyasn1 for sending and a custom faster asn1 decoder for received messages) and messages are built in a different way. I will play with it to understand how it works.—

**Comment by cannatag** [comment]
I understand this is a proof of concept. It's not clear to me what are the message types missing in the ldap3 rfc4511 definition. I started the project using pyasn1 and coded the full ldap3  protocol (with some extension for specific implementations). Then when the library became quite stable I rewrote the ash1 decoding function (achieving a 10x speed improvement over pyasn1). Didn't rewrote the encoder because being a client library few messages are sent and many are received (this is something I'd like to do while proceeding in the sldap3 project).

Your code is interesting and will play with in in the weekend.

Thanks,
Giovanni

**Comment by mistotebe** [comment]
I've hit a few snags getting an asyncio support[0] for python-ldap and just discovered this module.

Looking at the proposal here, it is not too unlike what I've been trying to do there but since I need to support syncrepl, the response queue part is slightly different, but allows for the caller to decide whether they expect intermediate responses returned for any operation (some controls could cause that). Should we try and revive this effort?

Same question applies again, is it better we go the aioldap3 route or add a new strategy/connection class? At first glance, the strategy route looks a bit harder to reconcile with supporting intermediate responses for an operation.

As for the TLS support, wrapping has been merged into 3.7[1], so that shouldn't be a problem anymore.

[0]. https://gist.github.com/mistotebe/7bbc48ce20c8dc82f6885b370353be60#file-ldap_wrapper-py
[1]. https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.start_tls

**Comment by mistotebe** [comment]
I've had a stab at this and this is a work in progress to see if I can get anywhere close:
https://github.com/mistotebe/ldap3/tree/asyncio

**Comment by cannatag** [comment]
Thanks, I actually don’t use asyncio, so I cannot review your code. Let me know when you think this strategy can be included in the main project. 

Don’t hesitate to ask if you need help!

Bye,
Giovanni

**Comment by mistotebe** [comment]
Hi Giovanni,
thanks for the response, I will definitely need some structural feedback later on once I have to disentangle the request-response processing from Connection/Strategy (`post_send_single_response` and afterwards) since that refactoring probably needs to make it back into how the main Connection class deals with it.

In the meantime, any thoughts on https://github.com/mistotebe/ldap3/commit/c09624f2ad17878b2dfb0d9f748d57758f29dc22?

**Comment by remidebette** [comment]
Hi,

We are using the ldap3 library and are pretty satisfied by it.
For performance reasons we are now interested in switching to an asyncio based server. Is the support of asyncio still considered in the ldap3 library?

Thank you

**Comment by Skeen** [comment]
Sorry for necromancery, but did anything ever happen with regards to this?
