### ISSUE TITLE
ldap3.core.exceptions.LDAPSizeLimitExceededResult exception message too long

### ISSUE THREAD

**Issue by brianmay** [cannatag/ldap3#20]
Hello,

Not sure if this has already been fixed or not, however with python3-ldap 0.9.6.2 I get this incredibly long exception message:

ldap3.core.exceptions.LDAPSizeLimitExceededResult: LDAPSizeLimitExceededResult - 4 - sizeLimitExceeded - None - None - searchResDone - [ < ....> ].

Where <...> lists every single result and every single attribute that was obtained before the size got too big.

This is huge.

Thanks

**Comment by cannatag** [comment]
Hello Brian,
when you get an exception (with raise_exceptions = True) I put the not yet elaborated response from the connection in the raised Exception. It's quite easy to remove the response letting only the result in the Exception, but if I do that you cannot read the response in any way because with raise_exceptions = True the Exception is raised as soon as the error result is returned by the server and the response is not yet elaborated. 

To check try to remove the "response=response" assignment from line 295 in the ldap3.strategy.base.py module (in 0.9.7.4). Do you think this is a correct behaviour in case  size (and time) limit are excedeed? Do you thinks it's better to have no entries at all instead of only those that are within the limit? (This make sense because if you get some entries and a limit exception you have no ways to ask for the remaining entries, this is, I think a flaw in the LDAP protocol itself).

Bye,
Giovanni

**Comment by cannatag** [comment]
I removed the response when raising the exception. FIxed in upcoming 0.9.7.5.

Bye,
Giovanni
