### ISSUE TITLE
Document the auto_range feature on the connection object

### ISSUE THREAD

**Issue by ashleybartlett** [cannatag/ldap3#212]
You have an incredibly useful feature on the connection object called auto_range, that is not documented. I eventually found it after some crazy google queries and a few hunches. 

Please document this.

This would be really useful to have enabled by default if you detect the server is Active Directory.

**Comment by cannatag** [comment]
Hi Ashley, you're right, I developed the auto_range feature has a workaround to the hard limit of 1000 entries returned in Active Directory searches but I forgot to mention it in the documentation. Will update docs soon.

 I can make it defaults to True because I don't think there is any drawback in keeping it always active, even because for what I know this feature is used by Active Directory only.

People don't know the awkward default limitation of 1000 entries in searches for Active Directory, so having it enabled can avoid strange behaviours when searches stop working properly when the 1000 entries limit is reached.

Bye,
Giovanni

**Comment by cannatag** [comment]
Documented on ldap3.readthedocs.io

**Comment by cannatag** [comment]
Version 2 of ldap3 non ships with the auto_range parametri set to True
