### ISSUE TITLE
load OpenLDAP settings automatically

### ISSUE THREAD

**Issue by skurfer** [cannatag/ldap3#213]
I suspect a lot of people using LDAP already have things like the URI, search base, etc. defined in `~/.ldaprc` or something similar. It would be nice if `ldap3` could use these settings automatically rather than requiring them to be repeated in code.

I’d be happy to add this ability via pull request, but I want to make sure you’re open to the idea first.

FYI, it would follow the same rules as OpenLDAP and check the following places for settings (from lowest to highest precedence):

  * System-wide `ldap.conf` (found in `/etc` or `/usr/local/etc`)
  * The user’s `~/.ldaprc`
  * A file named `ldaprc` in the current directory
  * Environment variables that have names beginning with “LDAP”

Of course, in the case of this library, settings defined in code would be respected above all the other sources.

**Comment by cannatag** [comment]
Hi Rob, I'm aware of the OpenLDAP client configuration methods. I didn't include it in the ldap3 library because for what I know this is not defined in any RFC and applies only  to Linux/Mac and other flavors of Unix. While developing ldap3 I strictly followed the  RFCS with really few exceptions. Now that the library is quite stable I'm working on a new abstraction layer, fully read and write capable that hope to release soon in version 2 of ldap3 that includes also some minor not backward compatible functionality updates. It could be a good idea to include your PR in the new version. Probably it should not be active by default but activated by some configuration parameter to avoid issues with people not aware of this configuration functionality.

Feel free to send the PR in dev, it should work even if I'm committing many changes in the ldap3.abstract namespace.

Thanks,
Giovanni

**Comment by skurfer** [comment]
Thanks. I’ll have a look at the dev branch.

Closing this issue. If anything comes of it, I’ll open a PR.

**Comment by skurfer** [comment]
I didn’t realize something had been done on this, so I released what I’ve been using. Leaving it here in case anyone prefers something independent from a specific LDAP library.

https://github.com/skurfer/ldaprc
