### ISSUE TITLE
Missing old versions on PyPI (Again)

### ISSUE THREAD

**Issue by jerrykan** [cannatag/ldap3#215]
Basically the same problem that was occurring in #54 and #85.

I have a dependency on v0.9.8.7 which no longer exists in PyPI.

Can you please ensure that old version of ldap3 remain on PyPI so as not to break existing deployments of production software.

**Comment by cannatag** [comment]
I know. I removed all version before 1.0 because of some little bugs and because thy are much slower. All version up to 1.4 should be compatible. Can't you upgrade your requirements?

If you're stuck with that specific version I can public a 0.9.8.7.post1 version with the 1.4 codebase. You should notice no difference at all.

Bye,
Giovanni

**Comment by jerrykan** [comment]
Systems are developed against specific versions of libraries because they have gone though testing/QA and are a known quantity. If a system needs to be redeployed, then there is a guarantee that it will (or should) behave exactly like the previous deployment because all the dependencies are exactly the same (hence why PyPI doesn't allow replacing files by deleting/re-uploading). By deleting old versions of the ldap3 library we can no longer provide this guarantee that the system will behave the same way as they did in testing/QA. Newer version of libraries my fix bugs, but they also change behaviour that a system may have been relying on.

Users should be allow to choose when to upgrade their dependencies so that they can do proper testing/QA and not have it forced upon them because old version are being deleting. In most cases developers will also find out at the worst possible time that old version no longer exist - ie. trying to redeploy a system as part of disaster recovery. This is definitely not the time that developer what to be dealing with trying to upgrade/QA/test dependency changes.

This basically all boils down to the fact that deleting old version of packages from PyPI is extremely bad practice, and there is generally never a good reason for doing so.

Can you please guarantee that you will *never* delete old packages version from PyPI?

**Comment by cannatag** [comment]
Hi John, 
I agree with you, I never delete a release of production code. ldap3 was in beta until 1.0. I gradually removed beta versions from pypi because of bugs and improvements and I strove to keep compatibility at the function signature level.

I'm surprised by the large usage of this library when still in beta. Many developers used in in their production code, regardless of the beta state. 

I will republish the version you need on pypi, but I strongly suggest to move to production quality code as soon as possibile.

**Comment by cannatag** [comment]
Version 0.9.8.7 is available again. its name is 0.9.8.7.p1.
