### ISSUE TITLE
Develop ldap3.extend.microsoft.unlockAccount module

### ISSUE THREAD

**Issue by kanayak123** [cannatag/ldap3#222]
I am developing a project which uses ldap3 for resetting Active Directory password. But I also need to unlock the locked the user accounts. I have patched ldap3.extend.microsoft.modifyPassword module, to enable this in my local platform. It works perfectly. But it would be great if this feature is included in the original build. It may be useful for many peoples. Requesting community to add this functionality. 

```
result = connection.modify(user_dn,
                           {'unicodePwd': [(MODIFY_REPLACE, [int(0)])]},
                           controls)

```

**Comment by cannatag** [comment]
Hi Kanayak. Thanks for your support. I'm about to release version 2 of ldap3. Will check your issue against that version.

**Comment by cannatag** [comment]
Hi Amith, could you point me to the official Microsoft document for the unlock account feature?

Thanks.
Giovanni

**Comment by cannatag** [comment]
I don't see how setting the password to 0 could unlock the user account. did you mean "lockoutTime"?

**Comment by mprahl** [comment]
@cannatag I'm not sure if this helps, but I reset Active Directory users using python-ldap with the following code:
```
# Active Directory requires the password be surround by quotes and be unicode encoded
encoded_password = ('"{0}"'.format('N3wP@ssw0rd')).encode("utf-16-le")
ldap_connection.modify_s('CN=Test User,OU=PostMaster,DC=postmaster,DC=local', [(ldap.MOD_REPLACE, 'unicodePwd', encoded_password)])
```

Additionally, documentation from Microsoft says:
> 
The second way to modify this attribute is analogous to an administrator resetting a password for a user. In order to do this, the client must bind as a user with sufficient permissions to modify another user's password. This modify request should contain a single replace operation with the new desired password surrounded by quotes. If the client has sufficient permissions, this password become the new password, regardless of what the old password was.
> 

Source: https://support.microsoft.com/en-us/kb/269190

**Comment by mprahl** [comment]
@cannatag I'm not sure if this helps, but I unlock Active Directory users using python-ldap with the following code:
```
ldap_connection.modify_s('CN=Test User,OU=Users,DC=domain,DC=local', [(ldap.MOD_REPLACE, 'lockoutTime', '0')])
```

**Comment by kanayak123** [comment]
Sorry, pasted the wrong code in my original comment. You are right it should be lockoutTime attribute.  The document I could get detailing about this attribute is here https://msdn.microsoft.com/en-us/library/ms676843(v=vs.85).aspx#win_2008_r2

**Comment by cannatag** [comment]
Good. Will include it in version 2.1. Thanks.

**Comment by cannatag** [comment]
2.1.0 released
