### ISSUE TITLE
Add support for SASL NTLM

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#24]
It would be nice if ldap3 would support SASL NTLM, to be able to bind to active directorY, that has no domain controller certificate enrolled.

**Comment by cannatag** [comment]
Hi,
is this urgent for you? 
I will include this request in the wish list for ldap3.

Bye,
Giovanni

**Comment by cornelinux** [comment]
Hi Giovanni,
thx for the reply. No not that urgent.
Wish list is fine!
Kind regards
Cornelius

**Comment by cannatag** [comment]
Hello Cornelius, 
I've gather some documentation and have been working on NTLM authentication this week. I have a working release in dev. It uses NTLM v2 only and doesn't need any additional package. It still has to be refined, but if you were able to give a try it would be very helpful for me because I have limited access to Active Directory servers. 

To test it you have to choose 'NTLM' as the authentication parameter in the Connection object and 'DOMAIN\\user' as user. You don't need to change anything else. For now it works only with the sync strategy.

Let me know if you succeed in using it.

Bye,
Giovanni

----- Messaggio originale -----
Da: "Cornelius Kölbel" <notifications@github.com>
Inviato: ‎23/‎02/‎2015 11:21
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] Add support for SASL NTLM (#24)

Hi Giovanni,
thx for the reply. No not that urgent.
Wish list is fine!
Kind regards
Cornelius

**Comment by cannatag** [comment]
You can also try 0.9.8.1 from pypi.

**Comment by cornelinux** [comment]
Hi Giovanni,

this worked for me on a Windows 2012R2:
Thx and kind regards
Cornelius


<pre>   
# import class and constants
from ldap3 import (Server,
                   Connection,
                   SIMPLE,
                   SYNC,
                   ALL,
                   SASL, NTLM)



# define the server and the connection
s = Server('172.16.200.141', port=389, get_info=ALL)
c = Connection(s,
           auto_bind=False,
           client_strategy=SYNC,
           user="AUTHTEST\\Administrator",
           password="password",
           authentication=NTLM,
           check_names=True)
c.open()
r = c.bind()
print r
print c.result
c.search("dc=auth-test,dc=org", "(objectClass=person)")
print c.response
c.unbind()
</pre>
