### ISSUE TITLE
last_logon attributes return [b'0'] and  [] (undefined behavior)

### ISSUE THREAD

**Issue by Evangelistic** [cannatag/ldap3#243]
If user didn't log on AD **_paged_search_** can return two values attributes:
1. 'lastLogon': [b'0']
2. 'lastLogon': []
If AD return 0 - everything works, but If AD return [] program crash on this row:
`entry['attributes']['lastLogon'].strftime('%m/%d/%Y')`
because **list** has no attribute 'strftime'.
I fixed this in my program by using additional check, but it's wring

**Comment by cannatag** [comment]
Hi, the ``entry['attributes']['lastLogon'].strftime('%m/%d/%Y')`` is in your code? You should check for the presence of the value before trying to format it. You can ask ldap3 to not return empty attributes with the ``return_empty_attributes`` parameter of the Connection object, but in this case you must check for the presence of the attribute before accessing its value.

**Comment by Evangelistic** [comment]
Hello. Yes, this is code in my program. Now i check what that method can return. If it return empty list i set default value equal 0, that convert to string. But this mistake hard to search, because we have different values attributes in one code. For example:
`    if entry['attributes']['lastLogon'] == []:
        entry['attributes']['lastLogon']=datetime.datetime(1601, 1, 1, tzinfo=None)`
This can be true?
p.s. I think default parameter must not be allowed undefined behavior. 
Thank you for module. Best regards.

**Comment by cannatag** [comment]
The problem you're facing is that LDAP protocol doesn't allow empty attributes. So when you receive '0' this means that your AD server returns 0, while when you receive [] it means that nothing has been sent by the server. You can avoid the empty list with ``return_empty_attributes=False`` but in this case you must check for the presence of the attribute before requesting its value. 
The return_empty_attributes has been added to avoid cluttering your code with ``if hasattr(entry['attributes']['my:attribute']: ...`` conditions, because only few attributes are mandatory in ldap.

In your case you can just use  ``if not entry['attributes']['lastlogon']: ...`` that catches both (0 and []) conditions or revert the ``return_emtpy_attributes`` to False.

**Comment by Evangelistic** [comment]
Thank you.
