### ISSUE TITLE
[Feature Request] Add Active Directory's "LDAP_MATCHING_RULE_IN_CHAIN" to Mock LDAP Server

### ISSUE THREAD

**Issue by mprahl** [cannatag/ldap3#244]
Hello,
I'm writing unit tests in a project that uses ldap3 for Active Directory authentication. One of the features specific to Active Directory is its "LDAP_MATCHING_RULE_IN_CHAIN" operator. Whenever I try to use this in my ldap3 tests, it fails.

A brief description from Microsoft explains: "this rule is limited to filters that apply to the DN. This is a special "extended" match operator that walks the chain of ancestry in objects all the way to the root until it finds a match." For more official information, visit https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx

This allows you to find nested group memberships of a user with a filter such as `(member:1.2.840.113556.1.4.1941:=cn=user1,cn=users,DC=x)`. It also allows you to find if the user is a member of a specific group (even if it is nested) by setting the base of the query to the distinguished name of the user, and a search filter of `(memberof:1.2.840.113556.1.4.1941:=cn=Group1,OU=groupsOU,DC=x)`.

Thanks for your help.

**Comment by cannatag** [comment]
Hi Matt, 
Don't think this can be added to the mock strategy in ldap3 because it's something specific to AD and not in the LDAP standard.

As you can guess the mock strategy is not a full ldap server! It covers the standard ldap operations. Extended operations are usually not defined in standard rfc and don't apply to all ldap servers. 

This doesn't mean that it cannot be done in a future version of ldap3, but I should implement some sort of plugins for different kind of servers so that they don't interfere with each other.

**Comment by mprahl** [comment]
@cannatag not a problem. I will just mock around it. Thank you for the quick feedback.
