### ISSUE TITLE
Switch from pyasn1 to asn1crypto (as cryptography does)

### ISSUE THREAD

**Issue by socketpair** [cannatag/ldap3#332]

**Comment by cannatag** [comment]
Hi, by default the pyasn1 library is used only for building messages to send to an LDAP server. When decoding messages from the LDAP server an internal ASN.1 decoder is used. I don't think I will switch to another asn1 library for now.

ì

**Comment by mikmatko** [comment]
Performance comparison would be interesting between the internal ASN.1 decoder vs. pyasn1 vs. asn1crypto. Any guesses whether there could be, even in theory, any performance gains from using asn1crypto instead of the internal ASN.1 decoder?

asn1crypto claims to be significantly faster than pyasn1, but then again, so is the internal decoder.

**Comment by etingof** [comment]
Just a quick note, that while asn1crypto is on average faster than pyasn1 as it stands now, performance difference depends heavily on the data you are trying to decode. 

So I think the comparison would be most fruitful if you test various decoders on samples of your data  -- the complexity of decoding algorithms vary depending on the ASN.1 data types and way it's encoded.

One of the reasons for pyasn1 being slower is that it performs constraints validation, as ASN.1 spec has it. 

I think if you are targeting highest possible performance, the best bet would be to write a very rigid, special-purpose codec. That will let you optimize heavily for your use-case ignoring all the edge-cases that you'd otherwise have to account for. I believe this is what Giovanni did in the first place. If you look at the `libsnmp` project, that would be another example of a simple and fast decoder.

**Comment by cannatag** [comment]
I agree with Ilya, the internal ASN.1 decoder of ldap3 is "tailored" for LDAP messages, and only for decoding them. Also it doesn't perform any constraint checking. Also it assumes that received data is correct and that the BER coding is strictly followed by the server. In fact the whole decoder is only 212 lines long (including license, comments and blank lines). In ldap3 the ASN.1 encoding  is still done with pyasn1 for its excellent way of defining the "productions" described in the LDAP RFCs. 

Anyway to perform a comparison we need the LDAP  "production" (RFC4511) defined for the asn1crypto, and I have not found them anywhere. I don't know if there is a way to convert the pyasn1 code definitions to asn1crypto or if it uses a different approach.
