### ISSUE TITLE
connection strategy REUSABLE is getting connection.server.schema only on when first connected

### ISSUE THREAD

**Issue by saipydev** [cannatag/ldap3#335]
code:
conn = Connection(server, username, pwd, client_startegy=REUSABLE)  
obj_def = ObjectDef(['fooMethod'], conn)

ObjectDef is raising LDAPSchemaError('schema not present') when i run the program  second time.

**Comment by cannatag** [comment]
Hi,
the connection must be bound because the ObjectDef must read the schema to build the correct AttrDef list. Also the REUSABLE client_strategy is quite complex to use and is intended for multiple threading access to the LDAP server. If you don't need this you can use the RESTARTABLE or the SYNC client_strategy.

so in your code just add ``conn.bind()`` before defining obj_def. The 'fooMethod' object_class must exist in the schema for automatically read the schema and build the correct AttrDef list.

**Comment by sreesaikiran** [comment]
yes i have added conn.bind() but still works for first time and on second time run it errors me with 
raise LDAPSchemaError('schema not present')
ldap3.core.exceptions.LDAPSchemaError: schema not present
Looks like the conn.server.schema is returned as None
Moreover i need connection pooling so i'm using the REUSABLE strategy

**Comment by cannatag** [comment]
What you means with "second time run"? You mean that you close your program and then start it again or that the code is run a second time in the same program execution?

Can you send the real snippet of code that is failing?

**Comment by sreesaikiran** [comment]
conn = create_connection(host, account, password)
conn.bind()
obj_def = ObjectDef(['fooMethod'], conn)
print(obj_def)
conn.unbind

conn = create_connection(host, account, password)
conn.bind()
obj_def = ObjectDef(['fooMethod'], conn)
print(obj_def)
conn.unbind

**Comment by cannatag** [comment]
The second connection is using the same "pool of connections" of the first one. You must specify a different pool in the connection or use the conn.strategy.terminate() method before creating the second connection:

```
from ldap3 import Server, Connection, REUSABLE, ObjectDef
server = 'edir1'
username = 'cn=admin,o=resources'
pwd = 'password'

conn = Connection(server, username, pwd, client_strategy=REUSABLE, pool_name='POOL1')
conn.bind()
obj_def = ObjectDef(['inetOrgPerson'], conn)
print(conn.strategy.pool)
print(obj_def)
conn.unbind()
# conn.strategy.terminate()  # alternative to using 2 different pools

conn = Connection(server, username, pwd, client_strategy=REUSABLE, pool_name='POOL2')
conn.bind()
obj_def = ObjectDef(['inetOrgPerson'], conn)
print(obj_def)
conn.unbind()
```

The ldap3 libray keeps the pool of threaded connections after the unbind() method because you could open the same connection again. If you really want to destroy the pool use the conn.strategy.terminate() method that closes all the threads. If you specify different pools for different connections you can use both pools simultaneously.

I'm not sure what is better for your application but both should works.
