### ISSUE TITLE
Expose MOCK_ASYNC strategy

### ISSUE THREAD

**Issue by nanonyme** [cannatag/ldap3#347]
Hey,
as a third-party library trying to integrate against ldap3, it would be preferrable if MOCK_ASYNC was officially exposed. Are there any missing features on the front or how come it's masked from being used?

**Comment by cannatag** [comment]
MockAsync is still not complete, must work on it.

**Comment by cannatag** [comment]
Hi,
the  MockAsync strategy works now, you can use it with client_strategy=MOCK_ASYNC when defining the Connection object. Can you try the code in dev?

Thanks,
Giovanni

**Comment by nanonyme** [comment]
I'm a bit embarassed to say but I refactored the entire library today so SYNC would be enough since I didn't know how long the ASYNC would take to be done.

**Comment by cannatag** [comment]
No problem! The MockAsync strategy was almost completed, it took less than an hour to finish it. I really don't remember why I didn't finish it when I wrote the MockBase strategy.

Anyway the Sync strategy is, in my opinion, better and simpler to use and also a bit faster because it doesn't involve threading.

Bye,
Giovanni
