### ISSUE TITLE
Missing usage counting for SyncMockStrategy and AsyncMockStrategy

### ISSUE THREAD

**Issue by joehybird** [cannatag/ldap3#369]
Hello,

I would like to make some tests with "search_operations" statistics, but it seems that mock strategies doesn't entirely support it. For SyncStrategy it seems that BaseStrategy.sending() updating these stats and it is not called in MockSyncStrategy (or i missed something).

Could you add this feature in the future ?

**Comment by cannatag** [comment]
Hi, you're right, the metrics were not updated in Mock strategies. I've fixed this in dev. Now metrics are updated except for the total bytes received by the server because there is no real server in the mock strategy.

Please check code in dev and let me know if this is good for you.
Thanks,
Giovanni

**Comment by cannatag** [comment]
Fixed in release 2.3 of ldap3.
