### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by mnosenko** [cannatag/ldap3#399]
Good day.
I haven't found function with reseting password in Active Directory (package ldap3.extend.microsoft ).
I've found only change password (with inserting old password).
I (and, maybe, other administrators and developers) would have the opportunity reset password from python for adding buttonc click function for resetting password or set password with creating many users by script

**Comment by cannatag** [comment]
If you have administrative privileges just use the modify_password() function with the new password only. It will perform a password reset. Remember that you must use a secure connection for changing/resetting the password.

Giovanni

**Comment by jtcressy** [comment]
So this issue is still a problem.

I have an active directory server with SSL enabled...
let ``c = ldap3.Connection()`` where i've connected over ssl on port 636 and a successful bind with a user in the "Domain Admins" group.
let ``user_dn`` = a valid distinguished name for a normal user
When I execute ``c.extend.microsoft.modify_password(user_dn,"newpassword")``
It fails, with ``c.result`` being error "unwilling to perform"
The user I bind with is able to change the user's password in the "active directory users and groups" dialog on a windows machine. So there are no permissions issues.

What am I missing?
