### ISSUE TITLE
How to search for entries more than 1000 

### ISSUE THREAD

**Issue by cinguva** [cannatag/ldap3#427]
Hi All,
Right now i am using ldap3 module in one of my Python Scripts to query a OU in AD. Despite of settting paged_size = xxxxxx(>1000),  i receive only upto 1000 values. I know there is a limitation for AD search, How can i search for other entries >1000.

**Comment by okin** [comment]
The trick is to set _paged_size_ to a value lower or equal your server-side limitation.

**Comment by cinguva** [comment]
I apologize for not following, if i do a page_size less that server limitation, how would i iterate through next pages?

**Comment by Busuwe** [comment]
The easiest way is to use extend.standard.paged_search(...) which will take care of fetching all pages of the search. Otherwise you need to retrieve the cookie from each page and use that to fetch the next page.
There is an example in the docs on how to manually request subsequent pages, and below that you'll find an example of paged_search(...): http://ldap3.readthedocs.io/searches.html#simple-paged-search

**Comment by cinguva** [comment]
Thank you Busuwe, it helped me fetch the results. Thanks again for guiding me there.

Cheers
Chander
