### ISSUE TITLE
Weird issue resulting in "*** ldap3.core.exceptions.LDAPSocketOpenError: invalid server address"

### ISSUE THREAD

**Issue by jeromegit** [cannatag/ldap3#442]
I have been using ldapsearch for years but decided to go "native python" for my first django app.
I use the following command:
`dapsearch -D "cn=xxx,cn=users,dc=wwww,dc=zzzz,dc=com" -w my_pass -h my_host -p 3268 -b dc=com "(sAMAccountName=login_name_to_look_up)" `
When I try to do the same with:
```
from ldap3 import Server, Connection, ALL
server = Server('my_host', port=3268, get_info=ALL)
conn = Connection(server, "cn=xxx,cn=users,dc=wwww,dc=zzzz,dc=com", "my_pass", auto_bind=True)
conn.bind()
conn.search('dc=org', '(objectclass=person)')
```
When run this iteractively, conn.bind() returns True
conn.result returns:
`{'dn': '', 'saslCreds': None, 'result': 0, 'message': '', 'description': 'success', 'type': 'bindResponse', 'referrals': None}`
server.info returns a ton of lines
But when I try to runn the `conn.search('dc=org', '(objectclass=person)')` I get the following exception:
`*** ldap3.core.exceptions.LDAPSocketOpenError: invalid server address`

How can the server address be invalid when I can connect, bind, get info?

Please help.

Thanks.

**Comment by kiddick** [comment]
Looks like issue is here:
you are binding with cn=xxx,cn=users,**dc=wwww,dc=zzzz,dc=com**
and trying to search within **dc=org**

You are getting this error probably due to `auto_referrals=True` in `Connection` by default. Try to use:
`conn = Connection(server, "cn=xxx,cn=users,dc=wwww,dc=zzzz,dc=com", "my_pass", auto_bind=True, auto_referrals=False)` and do not search and another DC.

**Comment by jeromegit** [comment]
Duh!
Thank you so much Kiddick!
