### ISSUE TITLE
How to connect to ldap:///dc%3Dmydomain%2Cdc%3Dlocal ldapuri?

### ISSUE THREAD

**Issue by joernheissler** [cannatag/ldap3#485]
Hello,
with ldapsearch, I can use `-H ldap:///dc%3Dmydomain%2Cdc%3Dlocal`  (urlencoded for `ldap:///dc=mydomain,dc=local`) to connect to an URI instead of a specific server.
Does the python ldap3 package support that too?
Cheers

**Comment by cannatag** [comment]
RFC4516 has this in the example of valid ldap urls, but I'm not sure of what this should means. Probably you have the default server defined in some configuration files?

**Comment by joernheissler** [comment]
Sorry, forgot to mention: ldapsearch will query the DNS for SRV records of "_ldap._tcp.mydomain.local". The DNS server replies with a list of all the active-directory servers.

**Comment by joernheissler** [comment]
https://tools.ietf.org/html/rfc3088 is the only RFC that I can find about this.
Microsoft makes active use of this feature: https://technet.microsoft.com/en-us/library/cc961719.aspx (Not sure if there's a newer document).
And not sure if anyone else (e.g. openldap) actually use this. I think it's a nice feature because I, as a user, won't get noticed out of band when the windows admins move their AD servers to new hosts.

**Comment by cannatag** [comment]
I've found http://ldapwiki.com/wiki/Verify%20DNS%20Records that expain how to request for the ldap SRV. It should search for all record of type _ldap._tcp and then choose one of the returned ip for opening the connection. So there should be an implicit bind to the found server. Is this right?

**Comment by joernheissler** [comment]
Currently I'm querying DNS with dnspython and building a ServerPool from the result.
I explicitly call bind() on the connection object.

So I'm not sure what you mean with "implicit" here. Probably I've got problems with terminology here; I'm by no means at all an ldap expert.

**Comment by cannatag** [comment]
Yes, that is the right approach. The problem in including this in ldap3 is that with the standard python library it seems that I cannot query for SRV records, and I prefer to not have additional dependencies (other than pyasn1) from other libraries. I should find some very simple dns resolver to include directly in the ldap3 code, maybe with an automatic option to ignore it if the dnspython library is present.

Forget me for the “implicit” binding. There is nothing like that in ldap3, I meant “anonymous” but this is not relevant anyway because you can pass the credential in the Connection object, so the standard bind() operation can be used.

Bye,
Giovanni

**Comment by joernheissler** [comment]
> other than pyasn1

Unrelated to the issue, but do you know about https://github.com/wbond/asn1crypto?
I like it much better than pyasn1.

**Comment by cannatag** [comment]
Hi, thanks for your suggestion. 
ldap3 uses a custom ASN1 decoder when receiving data from the server, pyasn1 is used only for building messages to send to the server. The internal decoder is very faster than pyasn1, so I don't think there is a need to change to a different ASN1 library, because I had to rewrite all the "production" definitions.
