### ISSUE TITLE
Slow response?

### ISSUE THREAD

**Issue by velopokatun** [cannatag/ldap3#534]
Good afternoon. You have a great library. But is it possible to accelerate the search as quickly as possible? Maybe I'm not doing something right. I compare ldap3 and bonsai in asynchronous mode. And the difference in the answer is huge.
```

"""
depend bonsai:
 apt-get install libsasl-dev,libldap2-dev,python3-dev,libkrb5-dev,libsasl2-dev

"""

from time import time
from asyncio import get_event_loop

from ldap3 import Server, ALL, Connection, ALL_ATTRIBUTES
from bonsai import LDAPClient

host, port = 'xxx', 389
user = 'cn=name,ou=user,dc=test,dc=wt'
pswd = 'test'

dn = 'dc=test,dc=wt'
filter = 'cn=yyy'


async def test_bonsai():
    client = LDAPClient("ldap://{}:{}".format(host, port))
    client.set_credentials("SIMPLE", (user, pswd))
    async with client.connect(is_async=True, timeout=2.0) as conn:
        res = await conn.search(dn, 2, filter)
        print(res)


loop = get_event_loop()

start_bonsai = time()
loop.run_until_complete(test_bonsai())
stop_bonsai = time() - start_bonsai


server = Server(host=host, port=port, use_ssl=False, get_info=ALL)


def test_ldap3():
    with Connection(server,
                    auto_bind=True,
                    client_strategy='ASYNC',
                    user=user,
                    password=pswd
                    ) as conn:

        id_mess = conn.search(search_base=dn,
                              search_filter='({})'.format(filter),
                              attributes=ALL_ATTRIBUTES,
                              )
        print(conn.get_response(id_mess))


start_ldap3 = time()
test_ldap3()
stop_ldap3 = time() - start_bonsai

print('ldap3:  ', stop_ldap3)
print('bonsai: ', stop_bonsai)
```

And here is the result itself:
```
ldap3:   0.411 sec
bonsai:  0.008 sec
```
What am I doing wrong? What is the difference? 

Thank you

**Comment by cannatag** [comment]
Hi, first of all bonsai is mostly written in C and uses libldap2 on Unix platforms and WinLDAP on Microsoft. ldap3 is all pure python, so it's inherently slower.
Also the "get_info=ALL" parameter of th Server connections means that when you open the connection the whole schema and the whole server info are read from the server (this is requested by the LDAP v3 protocol specification). I don't think that the bonsai library do the same. 
Also, the "ASYNC" strategy is a bit slower because when instances it creates a new python thread and doens't use an async loop.

Lastly in your code you're summing up the bonsai test time to the ldap3 time so the ldap3 result includes also the bonsai time!

I dont' have bonsai installed but I get the following result for ldap3 in my lab:

all info, ASYNC strategy: 1.7 seconds
no info, ASYNC strategy: 0.21 seconds (get_info=NONE in server object, check_names=None in connection object)
no info, SYNC strategy: 0.03 seconds

This is probaly still slower than a C search but I think it's quite fast in a pure python library.

Can you adapt your code with the following and test it in your environment?

```
server = Server(host=host, port=port, use_ssl=False, get_info=NONE)


def test_ldap3():
    with Connection(server,
                    auto_bind=True,
                    client_strategy='ASYNC',
                    user=user,
                    password=pswd,
                    check_names=False
                    ) as conn:

        conn.search(search_base=dn,
                    search_filter='({})'.format(filter),
                    attributes=ALL_ATTRIBUTES,
                    )
        # print(conn.get_response(id_mess))


start_ldap3 = time()
test_ldap3()
stop_ldap3 = time() - start_ldap3
```

Let me know the results.
Bye,
Giovanni

**Comment by velopokatun** [comment]
Thank you very much for your answer.

I apologize for the mistake about the time. Just did not notice. The final result with the corrections proposed by you here is :
```
ldap3:  0.156432 
bonsai: 0.005849
``` 
What's not so bad. And what is the output data to be duplicated with raw_: b "" and just dn: "".
Example : 
```
{'raw_dn': b'uid=555,ou=free,ou=users,dc=test,dc=wt',
 'dn': 'uid=555,ou=free,ou=users,dc=test,dc=wt',...}
```
Can I disable the output of raw and will not the response be even faster?

**Comment by cannatag** [comment]
Raw data is what is received over the wire  and is needed for processing the response from the server. I don’t think that removing it from the response wil make it faster, and it’s helpful to have it in case you have some problems while decoding the message from a flaky server (sometimes the server does not return the di in utf-8 as specified by the LDAP RFCs).
