### ISSUE TITLE
Cannot access 0.9.8.2 from pypi anymore

### ISSUE THREAD

**Issue by jwineinger** [cannatag/ldap3#54]
Hi, I've got a package that has a pinned requirement to 0.9.8.2 which doesn't seem to be available anymore on pypi. I'm just wondering if that was removed from pypi for a specific reason, or if it would be possible to keep old versions available there.

thanks!

**Comment by cannatag** [comment]
Hi Jay, I removed 0.9.8.2 because there was a bug in the dual stack (ipv4 and ipv6) support. It is fixed in 0.9.8.4. Can't you use that version? It is fully compatible with 0.9.8.2. Anyway if you can't update your requirements i will put 0.9.8.2 back for a while.

Thanks,
Giovanni


----- Messaggio originale -----
Da: "Jay Wineinger" <notifications@github.com>
Inviato: ‎27/‎05/‎2015 20:59
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Oggetto: [ldap3] Cannot access 0.9.8.2 from pypi anymore (#54)

Hi, I've got a package that has a pinned requirement to 0.9.8.2 which doesn't seem to be available anymore on pypi. I'm just wondering if that was removed from pypi for a specific reason, or if it would be possible to keep old versions available there.
thanks!

**Comment by jwineinger** [comment]
Hi Giovanni, 

Yes, I've already updated my package to use it but removing the version from pypi that I was pinned to broke my automated deployment. 

Might I suggest not removing old versions unless there is a (severe) security vulnerability in the code? Bugs and fixes are natural parts of software development and, to me, doesn't seem to require the removal of old versions. Having versions disappear makes it difficult to depend on and breaks the idea of pinning requirements. I'll end up having to self-host the versions I'm pinned to somewhere else (which is probably not a bad idea anyway).

thanks again

**Comment by cannatag** [comment]
Hello Jay, 
I tought the dual stack bug was quite severe, but you're right. If your build is working this means that the bug is irrelevant to you. So I put back the 0.9.8.2 and 0.9.8.3 (anyway I removed the bug from that code, actually using the 0.9.8.4 codebase). I have to add "post1" to the versions (so thy are 0.9.8.2.post1 and 0.9.8.3.post1, following the pep 440 guidelines (pypi denies to upload the same filename twice, even if you delete it). The "postN" suffix should be ignored by pip and other installers so you should be able to get it with the 0.9.8.2 requirement.

Sorry for the inconvenience, let me know if you still have problems-

Bye,
Giovanni
