### ISSUE TITLE
Falsy defaults in AttrDef are not used

### ISSUE THREAD

**Issue by f3anaro** [cannatag/ldap3#68]
Default values for an `AttrDef` that are falsy, will not be used. For example:

```python
user = ObjectDef()
user += AttrDef('memberOf', key='groups', default=[])

# Load an user entry that has no "memberOf" attribute with a reader
# If you now access the "groups" attribute of the entry ...
entry.groups

# ... you get
ldap3.core.exceptions.LDAPKeyError: 'key not found'
```

The problem is the test for default values in [reader module](https://github.com/cannatag/ldap3/blob/83716c821a94bc2d0965abcf8c61a075a048753b/ldap3/abstract/reader.py#L306).

**Comment by cannatag** [comment]
Thanks Lucas, I will check your fix soon.

Bye,
Giovanni

**Comment by cannatag** [comment]
Hi Lucas, can you try to change line 306 in ldap3.abstract.reader.py from:
            if name or attr_def.default:  # attribute value found in result or default value present
to:
            if name or attr_def.default is not None:  # attribute value found in result or default value present

Adding "is not None" should permit to use False or empty values as default. Leaving default to None doesn't set any default.

Let me know if this fix your problem.

Thanks,
Giovanni

**Comment by f3anaro** [comment]
If you look properly to my fix, there is a commit (f3anaro/ldap3@6d2303883) that do exactly what you proposed. But maybe someone (like me!) want `None` as default value in their application.

**Comment by cannatag** [comment]
Sorry Lucas, I thought you wanted empty values allowed as attribute default, not None too. I will read your commit carefully and will fix the code.

Thanks,
Giovanni

----- Messaggio originale -----
Da: "Lucas Kahlert" <notifications@github.com>
Inviato: ‎22/‎06/‎2015 15:33
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] Falsy defaults in AttrDef are not used (#68)

If you look properly to my fix, there is a commit (f3anaro/ldap3@6d23038) that do exactly what you proposed. But maybe someone (like me!) want None as default value in their application.

**Comment by cannatag** [comment]
Hello,
instead of creating a nodefault object can you please try the following:

in ldap3.abstract.attrDef.py change line 48 to:
    def __init__(self, name, key=None, validate=None, pre_query=None, post_query=None, default=NotImplemented, dereference_dn=None):

and in ldap3.abstract.reader.py  change line 306 to:
    if name or attr_def.default is not NotImplemented:  # attribute value found in result or default value present - NotImplemented allows use of None as default

This works in your tests. Using NotImplemented (a singleton data type similar to None) we don't need a new object (nodefault) and the import in reader.py.

Tell me if this is ok for you.

**Comment by f3anaro** [comment]
Hey :) Thanks for the improvement! I've pushed your suggestion. Would you merge it now?

By the way: would release a new pip version of your package? I use it in a bigger project and would like to include this "fix" from the cheeseshop instead of git.

**Comment by cannatag** [comment]
Will merge and release 0.9.8.5 in a few days.

Bye,
Giovanni

----- Messaggio originale -----
Da: "Lucas Kahlert" <notifications@github.com>
Inviato: ‎23/‎06/‎2015 00:55
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] Falsy defaults in AttrDef are not used (#68)

Hey :) Thanks for the improvement! I've pushed your suggestion. Would you merge it now?
By the way: would release a new pip version of your package? I use it in a bigger project and would like to include this "fix" from the cheeseshop instead of git.

**Comment by f3anaro** [comment]
Thanks a lot!

**Comment by cannatag** [comment]
releasing 0.9.8.5

**Comment by f3anaro** [comment]
De nada :)
