### ISSUE TITLE
Creating new object with Writer from ObjectDef fails

### ISSUE THREAD

**Issue by Sohalt** [cannatag/ldap3#751]
If I create a `Writer` from an `ObjectDef` and then try to create a new object it fails with
`ldap3.core.exceptions.LDAPCursorError: attribute 'objectclass' not defined`.

example:

```python
…
group = ObjectDef('groupOfUniqueNames')
w = Writer(connection, group)
w.new('cn=foo,ou=groups,dc=example,dc=com')
…
```

I would expect this to work, since the objectclass is given as part of the `ObjectDef`.

**Comment by cannatag** [comment]
In order to automatically create the object definition you must specify the connection where the object is defined whrn using ObjectDef: ” group = ObjectDef('groupOfUniqueNames', connection)”. When the second parameter is set to a connection or a server or a schema ObjectDef will build the group object with all the relevant attribute definitions.

**Comment by Sohalt** [comment]
Thanks!
