### ISSUE TITLE
LDAP [SSL: BAD_LENGTH] bad length (_ssl.c:2361)

### ISSUE THREAD

**Issue by jmcgrath207** [cannatag/ldap3#752]
Hey all I am having some weird issues where I am getting SSL errors randomly when I do LDAP queries. 95% of the time it works as  intended.  I have a feeling it's because of the `tls_configuration = Tls(validate=ssl.CERT_NONE)` part but I am not certain. 

Here is the version of the Library 
ldap3==2.6
python 3.7.4

Logs
```log
Traceback (most recent call last):
  File "./service_request/ad_ldap/service.py", line 12, in single_user_lookup
    lookup.search(LDAP_BASE_DN, filter, attributes=attrs)
  File "/usr/local/lib/python3.7/site-packages/ldap3/core/connection.py", line 788, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/local/lib/python3.7/site-packages/ldap3/strategy/restartable.py", line 190, in send
    raise LDAPMaximumRetriesError(self.connection.last_error, self.exception_history, self.restartable_tries)
ldap3.core.exceptions.LDAPMaximumRetriesError: LDAPMaximumRetriesError: restartable connection failed to send/Exception history:/    0 <class 'ldap3.core.exceptions.LDAPSocketSendError'>: socket sending error[Errno 104] Connection reset by peer/    1 <class 'ldap3.core.exceptions.LDAPSocketSendError'>: ("('socket sending error[SSL: BAD_LENGTH] bad length (_ssl.c:2361)',)",)/    2 <class 'ldap3.core.exceptions.LDAPSocketOpenError'>: unable to send message, socket is not open/Maximum number of retries reached: 5
```
Code
```python
import ssl
from ldap3 import Server, Connection, RESTARTABLE, set_config_parameter, Tls

tls_configuration = Tls(validate=ssl.CERT_NONE)

server = Server(host=LDAP_HOST, port=LDAP_HOST_PORT, use_ssl=True, tls=tls_configuration)


set_config_parameter('RESTARTABLE_SLEEPTIME', 3)
set_config_parameter('RESTARTABLE_TRIES', True)

ldap_conn = Connection(server, user=LDAP_USERNAME, password=LDAP_PASSWORD, auto_bind=True, client_strategy=RESTARTABLE)

ldap_conn.search(LDAP_BASE_DN, filter, attributes=attrs)

print(ldap_conn.entries[0])
```

**Comment by zorn96** [comment]
@jmcgrath207 this may relate to the server's certificate chain and your operating system's underlying version of whatever SSL library your python links against.
The problem doesn't appear to be in ldap3, but ldap3 is unfortunately lightly obscuring the original cause of the error by not bubbling up the raw SSL exception.

To try to help solve the problem:
Different SSL libraries have different limitations on the maximum length of certificate chain that they can validate. An easy example is that google chrome and firefox have different limitations on cert chain lengths that they'll validate for https. A more nuanced example is that, on linux-based operating systems, different packages will either link against LibSSL (OpenSSL) or GnuTLS, and which one is used (and its version) can cause bugs/behavioral differences.


Even though you're not trying to validate the cert, underlying SSL libraries can still trip over it. For example, GnuTLS on Ubuntu 14.04 cannot validate RSA-PSS certificates, and even if you tell it "don't try to validate the cert" the library hits an error handling the cert before it realizes that it shouldn't care (this issue was fixed in Ubuntu 16, and was not present for anything that built against OpenSSL).
See https://bugs.archlinux.org/task/54186 for an example of issues that these obscure SSL build oddities have caused for people trying to use LDAP specifically. 

Your server could be sending a chain of certificates that's too long for your system to be able to handle (this could also be a result of server misconfiguration since some servers don't validate their intermediate ca certificate chains to ensure they're sane).
Your SSL packages could also be encountering another issue but bubbling it up poorly. I recommend trying to manually test establishing a TLS connection with your target server using the command line tools for whatever underlying SSL library you have on your system.

Hope that helps!
