### ISSUE TITLE
ssl.CERT_REQUIRED ignored if use_ssl=True

### ISSUE THREAD

**Issue by przecze** [cannatag/ldap3#812]
I'm connecting to a server whose certificate I have not registered in `certifi.where()` (what exactly location I use is irrelevant. What matters is that certificate verification should happen and fail).    Consider following examples:   
Example 1: configuration according to documentation. No exception is raised due to missing certificate
```
>>> server = Server(LDAP_SERVER, get_info=ALL, tls=Tls(validate=ssl.CERT_REQUIRED, ca_certs_file=certifi.where()), use_ssl=True)
>>> Connection(server, auto_bind=False).start_tls()
False
```
Example 2: expected behavior achieved after `use_ssl` is removed:
```
>>> server = Server(LDAP_SERVER, get_info=ALL, tls=Tls(validate=ssl.CERT_REQUIRED, ca_certs_file=certifi.where()))
>>> Connection(server, auto_bind=False).start_tls()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/tls.py", line 284, in _start_tls
    self.wrap_socket(connection, do_handshake=True)
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/tls.py", line 204, in wrap_socket
    wrapped_socket = ssl_context.wrap_socket(connection.socket, server_side=False, do_handshake_on_connect=do_handshake)
  File "/usr/local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 402, in wrap_socket
    return GreenSSLSocket(sock, *a, _context=self, **kw)
  File "/usr/local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 91, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 270, in do_handshake
    super(GreenSSLSocket, self).do_handshake)
  File "/usr/local/lib/python3.6/site-packages/eventlet/green/ssl.py", line 113, in _call_trampolining
    return func(*a, **kw)
  File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/connection.py", line 1264, in start_tls
    if self.server.tls.start_tls(self) and self.strategy.sync:  # for asynchronous connections _start_tls is run by the strategy
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/tls.py", line 280, in start_tls
    return self._start_tls(connection)
  File "/usr/local/lib/python3.6/site-packages/ldap3/core/tls.py", line 289, in _start_tls
    raise start_tls_exception_factory(LDAPStartTLSError, e)(connection.last_error)
ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)',)
```

This is from my analysis caused by this lines in _core/tls.py_
```
    def start_tls(self, connection):
        if connection.server.ssl:  # ssl already established at server level
            return False
```
So apparently when I pass `use_ssl` to Server constructor, the part with certificate validation in `start_tls` is skipped? Or maybe when I pass `use_ssl` I shouldn't need to call `start_tls` at all. In such case, why isn't certificate verification failing during server creation?

EDIT: used versions:
```
$ python3 --version
Python 3.6.10
$ pip freeze |grep ldap3
ldap3==2.7
```

**Comment by zorn96** [comment]
hi!

StartTLS (the start_tls function) is not the same as LDAP (use_ssl). use_ssl indicates that we should negotiate a connection using LDAPS, which is an older way of establishing a secure LDAP connection that originally was introduced with the LDAPv2 protocol. LDAPS negotiates TLS at the time of opening the connection, and has a different default port (636) than normal LDAP (389).

StartTLS is a newer way to negotiate, specified in [RFC4513](https://tools.ietf.org/html/rfc4513), which allows any plain LDAP connection to be negotiated up to a TLS connection. StartTLS as a concept (also called "opportunistic TLS") is not specific to LDAP and can also be found in other protocols like SMTP.
StartTLS is newer, can go over the same port as plain LDAP, and is formalized in the latest RFCs, so many vendors prefer it. But lots of vendors still support LDAPS (only a few even call it deprecated) because it's still heavily used.


So this is a matter of confusion. The start_tls function you're called is trying to execute the start_tls operation. But if you set use_ssl to true, then you're already using TLS as soon as you open the connection, and you cannot execute the start tls operation. that's why it hard codes a false return value,

does that make sense? it's not that cert validation is being skipped, but it's being done by other means.
if you do
>>> server = Server(LDAP_SERVER, get_info=ALL, tls=Tls(validate=ssl.CERT_REQUIRED, ca_certs_file=certifi.where()), use_ssl=True)
>>> conn = Connection(server, auto_bind=False)
>>> conn.open()
>>> conn.bind()

then on the open operation you should see the SSL error. you might see it on the bind depending on your version of the ldap3 package, as there we some changes to how auto binding works (it's not actually a boolean in latest versions)

hope this helped!
