### ISSUE TITLE
Missing old versions on PyPI

### ISSUE THREAD

**Issue by jerrykan** [cannatag/ldap3#85]
I am regularly hitting an issue where I have a specific ldap3 version in my requirements files but these older versions keep disappearing from PyPI (ie. v0.9.7.11 was only release in March but is no longer available - https://pypi.python.org/simple/ldap3/).

This is a real pain because I have specifically pinned certain versions of ldap3 because that is what has been tested against and provide a known working environment. It means that when I come back to work on a project after no touching it for a few month I can no longer recreate the known working environment because the old versions no longer exist.

Are these old versions being actively deleted? if so can they be restored, or at a minimum can older version no longer be deleted from this point onwards.

**Comment by jerrykan** [comment]
On a semi-related issue I have also noticed that there are no git tags for some of the newer versions available on PyPI.

**Comment by cannatag** [comment]
Hello John, you are right, I lost older versions when pyPI changed its naming policy (now file names must be unique and cannot be reused) a few months ago. I wasn't aware of this and when I had troubles with uploads (I had a bad deployment flow because I were used to release a version and then re-release it with the updated docs) I deleted all files in the pyPI repository hoping this could fix the problem. Then I moved from pyPI to readthedocs for hosting the documentation, but could not recreate the older version files. Now I know I could get around this problem with the "post" release option (for example 0.9.7.11.post1 could be a valid version for your requirements), but I really don't like this solution because it's quite obscure. 

Anyway the newer ldap3 versions are highly compatible with the older so you should have no problem to use them in your older projects.

If you still need a specific version I can recreate (even if I forgot some version tags, another my deployment mistake, sorry) and publish it on pyPI with the post1 option.

Bye,
giovanni

**Comment by jerrykan** [comment]
OK, all good. If all versions from now on stay in PyPI then that should work for me. I can just update my projects with the current version and know they will still exist some time in the future.
