### ISSUE TITLE
Documentation Bug or my understanding is wrong on SSL certs?

### ISSUE THREAD

**Issue by hrishy** [cannatag/ldap3#863]
Hi

In the documentation we have 
`tls = Tls(local_private_key_file='client_private_key.pem', local_certificate_file='client_cert.pem', validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1, ca_certs_file='ca_certs.b64')`

And in another place it mentions this
local_private_key_file: the file with the private key of the client
local_certificate_file: the certificate of the server

So what is local_certificate_file 

1. is it the certificate of the server or 
2. the certificate of the client making the connection to the ldap server.

If its the certificate of the client then if i have the certificate of the LDAP server where do i pass it 
and which parameter of the method  below ?

`tls = Tls(local_private_key_file='client_private_key.pem', local_certificate_file='client_cert.pem', validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1, ca_certs_file='ca_certs.b64')`

**Comment by zorn96** [comment]
hi! local_certificate_file is the certificate of the client, not the certificate of the LDAP server.

I guess I'd ask what use case you're trying to solve for:

Is the peer ldap server's certificate signed by the CA? do its SANs match the way you're addressing it in your connection? If so, then there's no need to use the ldap server's certificate anywhere. If the CA cert that signed its server cert is part of your CA cert bundle, then you don't need to know the ldap server's certificate at all because you trust the CA - this also allows it to change its cert non-disruptively.

Is the goal to pin the peer ldap server's certificate and say "I don't trust it if it changes"? Or is it not signed by a CA at all?
If either of these are the case, then what I would suggest trying is putting the peer's certificate in "ca_certs_file".
It's not a CA cert - but when you trust a CA cert, you trust the CA itself obviously, because root CAs sign their own certs. As a result, the overwhelming majority of SSL libraries will say "if the server's certificate perfectly matches a CA cert in the bundle, then trust it". So this will let you establish trust with the peer LDAP server even if it's cert is self-signed, and it will pin it.

Note: some SSL library implementations won't properly check things like certificate expiry if you trust a self-signed cert in this way. If your server's cert is signed by a CA, I recommend just establishing trust by adding the CA cert to your bundle :) 

hope that helps!

**Comment by hrishy** [comment]
Hi Azaria

Thank you so much for taking a look at this.
I have 3 certificates with me

DigiCertCA.pem
DigiCertHighAssuranceEVRootCA.pem
MyLDAP.pem

How do i validate that the LDAP server that i am connecting to is the one
that i should be connecting too ?
One way I can think of doing this is to get the LDAPServer's certificate's
fingerprint that I connected to and match it with the fingerprint of
MyLDAP.pem no ?

But in the LDAP3 library I don't see a way of doing this.

regards
Hrishy

**Comment by zorn96** [comment]
so the modern day standards of TLS rarely involve directly comparing the a server's certificate to a local file - the reason you would do that is if there's only one certificate the server should ever be allowed to have. You can do this if you don't want to deal with Certificate Authorities, but it sounds like that isn't a problem for you.

Here's how it generally works:
The server's certificate (MyLDAP.pem in this case it seems) specifies a field known as "Subject Alternative Names" (SANs). This field specifies "names" that can be used for the server - commonly hostnames and fully qualified domain names for servers (e.g. myserver.com).
So when you connect to the server, for TLS negotiation to succeed, you must be using an address that's included in the SANs. If a server only has "example.com", and I try to connect using "alias.com", TLS negotiation will fail because I say "I'm looking for alias.com" and the server says "hi! I'm example.com"

So the chain of trust essentially goes
"I trust this CA" --> "This CA trusts this server, and agrees that it has address A" --> "I'm looking for the server with address A" --> "I trust this server because the CA I trust said that it has address A"

By checking that the server's cert has a SAN matching the address you're connecting to, you ensure that nobody is impersonating the server. By checking that the server's cert was signed by a CA that you trust, you ensure that some entity that you trust has trusted the server to own the address it claims to own.

So is MyLDAP.pem signed by either DigiCertCA.pem or DigiCertHighAssuranceEVRootCA.pem? You can check this using openssl (exact command may differ depending on your system, but it should be google-able). You can also use openssl to figure out the SANs secured by MyLDAP.pem

You can also combine DigiCertCA.pem and DigiCertHighAssuranceEVRootCA.pem into a bundle and then not worry about the signer as long as one has signed it.

So then what you'd run on your client is as follows:

```
my_cert_path = 'my_client_cert.cert'  # the cert for the machine that's running this code
my_pkey_path = 'my_client_private_key.key'  # the key for the machine that's running this code
ca_cert_file_path = 'DigiCertHighAssuranceEVRootCA.pem'
server_hostname = 'my-demo-ldap-server.my-domain.com'  # the server I'm talking to

tls_config = Tls(local_private_key_file=my_pkey_path, local_certificate_file=my_cert_path, validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1, ca_certs_file=ca_cert_file_path)

# SSL settings work with both LDAPS and LDAP+StartTLS. See RFCs for the difference, but they're just different styles of TLS negotiation
myserver_using_port389_starttls = Server(server_hostname, tls=tls_config)
myserver_using_ldaps = Server(server_hostname, tls=tls_config, use_ssl=True)

starttls_conn = Connection(myserver_using_port389_starttls)
starttls_conn.open()
starttls_conn.start_tls()  # negotiating tls is an explicit operation with StartTLS

ldaps_conn = Connection(myserver_using_ldaps)
ldaps_conn.open()  # TLS is started at open time with LDAPS
```

**Comment by hrishy** [comment]
Hi Azaria

Your explanation is amazing. Thank you so much.
I got confused by the documentation.

So in my case the MyLDAP.pem is issued by
Issuer: C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2
High Assurance Server CA

So i tried ca_cert_file_path = 'DigiCertHighAssuranceEVRootCA.pem'
and it worked.

Thanks a ton.

regards
Hrishy

**Comment by cannatag** [comment]
Hi Azaria, thanks for yout excellent explanation!
