### ISSUE TITLE
SSL Error after Patchday

### ISSUE THREAD

**Issue by westaytroy** [cannatag/ldap3#913]
Hi, 

i am using ldap3 for a project and ran into a problem several times. After every patchday, after the DC Forest is patched the same issue appears: 

` ldap.search(config['LDAP']['UserSearchbase'],  File "\lib\site-packages\ldap3\core\connection.py", line 789, in search response = self.post_send_search(self.send('searchRequest', request, controls))
  File "\lib\site-packages\ldap3\strategy\base.py", line 298, in send
    self.sending(ldap_message)
  File "\lib\site-packages\ldap3\strategy\base.py", line 845, in sending
    raise communication_exception_factory(LDAPSocketSendError, type(e)(str(e)))(self.connection.last_error)
ldap3.core.exceptions.LDAPSocketSendError: ('socket sending error[SSL: BAD_LENGTH] bad length (_ssl.c:2457)',)`

ldap is issued like this: 
`LdapServer = Server(config['LDAP']['Domain'], port = 636, use_ssl = True, get_info=ALL,allowed_referral_hosts=[('*',True)])
ldap = Connection(LdapServer, config['LDAP']['UserDN'], config['LDAP']['Password'], auto_bind=True)`

Is it necessary to create a ServerPool with RoundRobin to avoid this? Is there any other possibility?

**Comment by zorn96** [comment]
hi @westaytroy ! 
what's happening on these patch days? are you installing windows updates and rebooting the controllers?

this error originates from the lower level python ssl libraries (which in turn build on your system SSL libraries), so they're not specifically an ldap3 issue, but I believe I may have some ideas for a workaround.

I've done a bit of searching and people have seen this error with other packages; others have seen this when using multiple processes to connect to the same server, and those cases were traced down to an issue in their system ssl libraries. but if you're seeing this after installing updates and windows reload or reboot, then I think that this might be a result of the server that your application is talking to changing silently during the updates. this seems to be a result of how you set up your connection to AD

I see that your server uses "config['LDAP']['Domain']"
with AD, the domain name is registered in DNS and resolves to all servers, allowing some amount of dynamic load balancing.
so "mydomain.com" might contain "server1.mydomain.com" and "server2.mydomain.com", and you can use "mydomain.com" in your connection and it works fine because it resolves in DNS to the ips for server1 and server2

however, "server1.mydomain.com" and "server2.mydomain.com" have different certificates. so if your connection is talking to server1, but then it goes down, your connection might move to server2 because that also is resolvable from the domain name.
if this happens, then your connection will hit this SSL error because it's trying to continue using the key/modulus/etc. it negotiated with server1, but server2 is different.
if servers reboot or reload during patch days, then this seems like it might be a likely scenario.
you could check if this is happening by running a packet capture during your patch days and see if your client switches where it's traffic is going throughout.

one option you could try to fix this is using the RESTARTABLE strategy for your LDAP connection. then if you encounter errors like this, your application can try to renegotiate the connection.
this should seamlessly handle using the domain name for AD in your connection without issue, though your logs will show failed connections followed by restart attempts during patch days, and things can still fail if all DCs are down at the same time for too long (but I'm assuming that's not an issue).
I've used this setup with AD in the past, and specifically used a RESTARTABLE connection to handle issues where the DC my application talked to changed

since you're not performing strict peer certificate checking, this will also handle cases where the peer certificate changes.

let me know if what I said makes sense/helps :)

**Comment by westaytroy** [comment]
Hi,

thank you so much for the detailed answer. You got the whole scenario right. The DCs are restarted on patchday and I too believe that the server switches on those oocasions. I will try the restartable strategy. The next planned patchday is between 11th and 13th of February. I will be back with further informations after that.

**Comment by zorn96** [comment]
no problem! from my understanding and experience this should hopefully resolve things.

in the `send(...)` function for the restartable strategy, it has this little blurb
```
    def send(self, message_type, request, controls=None):
        self._current_message_type = message_type
        self._current_request = request
        self._current_controls = controls
        ...
                try:
            message_id = SyncStrategy.send(self, message_type, request, controls)  # tries to send using SyncWait
            self._reset_exception_history()
            return message_id
        except Exception as e:
            if log_enabled(ERROR):
                log(ERROR, '<%s> while restarting <%s>', e, self.connection)
            self._add_exception_to_history(type(e)(str(e)))
        if not self._restarting:  # machinery for restartable connection
            self._restarting = True
            counter = self.restartable_tries
            while counter > 0:
                if log_enabled(BASIC):
                    log(BASIC, 'try #%d to send in Restartable connection <%s>', self.restartable_tries - counter, self.connection)
                sleep(self.restartable_sleep_time)
                if not self.connection.closed:
                    try:  # resetting connection
                        self.connection.unbind()
                    except (socket.error, LDAPSocketOpenError):  # don't trace socket errors because socket could already be closed
                        pass
                    except Exception as e:
                        if log_enabled(ERROR):
                            log(ERROR, '<%s> while restarting <%s>', e, self.connection)
                        self._add_exception_to_history(type(e)(str(e)))
                failure = False
                try:  # reopening connection
                    self.connection.open(reset_usage=False, read_server_info=False)
                    if self._restart_tls:  # restart tls if start_tls was previously used
                        if self.connection.start_tls(read_server_info=False):
# there's more here but this is the part I wanted to get to
```
which will get triggered automatically when a server goes down for updates and an operation fails like you were seeing

those calls to `self.connection.unbind` followed by `self.connection.open` should cause the connection to properly move to a new server and renegotiate TLS, because the `open` function has this bit which will select the next server that the restarted connection will go to explicitly, rather than solely using the implicit fallback via DNS that was happening before
```
                for candidate_address in self.connection.server.candidate_addresses():
                    try:
                        if log_enabled(BASIC):
                            log(BASIC, 'try to open candidate address %s', candidate_address[:-2])
                        self._open_socket(candidate_address, self.connection.server.ssl, unix_socket=self.connection.server.ipc)
                        self.connection.server.current_address = candidate_address
                        self.connection.server.update_availability(candidate_address, True)
                        break
                    except Exception as e:
                        self.connection.server.update_availability(candidate_address, False)
                        # exception_history.append((datetime.now(), exc_type, exc_value, candidate_address[4]))
                        exception_history.append((type(e)(str(e)), candidate_address[4]))
```

for reference, `_open_socket` will explicitly re-negotiate tls, so when we get back to `send` and retry with the restarted connection, we should be good to go
```
    def _open_socket(self, address, use_ssl=False, unix_socket=False):
        """
        Tries to open and connect a socket to a Server
        raise LDAPExceptionError if unable to open or connect socket
        """
        ...
                if use_ssl:
            try:
                self.connection.server.tls.wrap_socket(self.connection, do_handshake=True)
                if self.connection.usage:
                    self.connection._usage.wrapped_sockets += 1
            except Exception as e:
                self.connection.last_error = 'socket ssl wrapping error: ' + str(e)
                if log_enabled(ERROR):
                    log(ERROR, '<%s> for <%s>', self.connection.last_error, self.connection)
                raise communication_exception_factory(LDAPSocketOpenError, type(e)(str(e)))(self.connection.last_error)
 ...
```

in theory, if your server update is fast enough, and server becomes available again, you could even end up reconnecting to the same server instead of falling through to another because it will go through candidate addresses the same way the connection did when you first opened it, with the same dns-based ordering.
that's why the restartable strategy is also useful for scenarios where you change the peer cert and for servers that will idle timeout and close long-lived peer connections.

my personal opinion at least is that `RESTARTABLE` and the new `SAFE_RESTARTABLE` are the best strategies to use in any kind of long-running app using synchronous ldap communication

**Comment by westaytroy** [comment]
Hi, 
i used RESTARTABLE strategy and it worked out fine. Thanks again!

**Comment by zorn96** [comment]
woohoo! glad it helped @westaytroy
