### ISSUE TITLE
WINDOWS Kerberos SASL bind Fail

### ISSUE THREAD

**Issue by lokilak** [cannatag/ldap3#916]
I am trying to setup a new environment with Kerberos  for a pet web project, using example mentioned here https://ldap3.readthedocs.io/en/latest/bind.html for Kerberos  on windows environment and did the monkey patch mentioned here https://stackoverflow.com/questions/52279503/passwordless-python-ldap3-authentication-from-windows-client, I am not getting any exceptions but bind returns None, so i did debug and found that the error as **The server requires binds to turn on integrity checking if SSL\\TLS are not already active on the connection, data 0, v4563\x00** so when I used TLS(tls = Tls(validate=ssl.CERT_NONE,version=ssl.PROTOCOL_TLSv1_2) in the connection i am getting **winkerberos.GSSError: SSPI: InitializeSecurityContext: The token supplied to the function is invalid.**
I am not sure if i am missing something  with SSL or i am hitting Security Strength Factor (SSF). If any one can point me how to fix this it would be great.

**Comment by zorn96** [comment]
hi @lokilak ! so what you're encountering is Microsoft's new requirements around LDAP signing and channel binding
https://support.microsoft.com/en-us/topic/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows-ef185fb8-00f7-167d-744c-f299a66fc00a

the 2 relevant policies are LDAP signing requirements and LDAP channel bind token requirements.
the LDAP signing requirement can be fulfilled via SSL/TLS on the connection (which can be either LDAPS or LDAP+StartTLS). I'd need to see a snippet of your code to know if you're doing that 100% correctly, but I don't think that's the issue.
I think it's the bind token. the channel bind token requirement only applies to SASL binds and needs to be separately handled

the ldap3 library has only recently added support for channel bind tokens. the monkey patch you followed predates the existence of the simple server policies around channel bind tokens, as Microsoft only made them easily settable/turned them on by default in late 2020.
so you'd need to make manual updates to the files you're monkey patching with in order to get them to support CBTs

if it helps, I've already opened an issue to add better native windows kerberos support to the ldap3 library. https://github.com/cannatag/ldap3/issues/908
so hopefully we can do away with the monkey patching in its entirety eventually, and it can get all the same bells and whistles as the posix support for kerberos

in the near term, your options would be:
1. further update/patch the monkey patch to support CBTs
2. change the channel bind token policy in your domain and on your domain controllers to be "negotiate" or "none" instead of "undefined" or "required" ("undefined" defaults to "required" as of the latest windows AD behavior)
3. use a simple bind instead of a SASL bind, since CBT requirements don't apply to simple binds as they're not a reusable authentication across other protocol channels

hope that helps!

**Comment by lokilak** [comment]
> hi @lokilak ! so what you're encountering is Microsoft's new requirements around LDAP signing and channel binding
> https://support.microsoft.com/en-us/topic/2020-ldap-channel-binding-and-ldap-signing-requirements-for-windows-ef185fb8-00f7-167d-744c-f299a66fc00a
> 
> the 2 relevant policies are LDAP signing requirements and LDAP channel bind token requirements.
> the LDAP signing requirement can be fulfilled via SSL/TLS on the connection (which can be either LDAPS or LDAP+StartTLS). I'd need to see a snippet of your code to know if you're doing that 100% correctly, but I don't think that's the issue.
> I think it's the bind token. the channel bind token requirement only applies to SASL binds and needs to be separately handled
> 
> the ldap3 library has only recently added support for channel bind tokens. the monkey patch you followed predates the existence of the simple server policies around channel bind tokens, as Microsoft only made them easily settable/turned them on by default in late 2020.
> so you'd need to make manual updates to the files you're monkey patching with in order to get them to support CBTs
> 
> if it helps, I've already opened an issue to add better native windows kerberos support to the ldap3 library. #908
> so hopefully we can do away with the monkey patching in its entirety eventually, and it can get all the same bells and whistles as the posix support for kerberos
> 
> in the near term, your options would be:
> 
> 1. further update/patch the monkey patch to support CBTs
> 2. change the channel bind token policy in your domain and on your domain controllers to be "negotiate" or "none" instead of "undefined" or "required" ("undefined" defaults to "required" as of the latest windows AD behavior)
> 3. use a simple bind instead of a SASL bind, since CBT requirements don't apply to simple binds as they're not a reusable authentication across other protocol channels
> 
> hope that helps!

**Comment by lokilak** [comment]
Thank you very much, i will explore options to do enable  CBT in the current Patch and also will be watching for native windows kerberos support to the ldap3 library.
