### ISSUE TITLE
NTLM v2 auth errors out with "Invalid Credentials" error during bind due to lack of CBT support with NTLM

### ISSUE THREAD

**Issue by py-prash** [cannatag/ldap3#923]
I am trying to authenticate against active directory domain controller accepting only NTLM v2 hashes and it errors out at the bind step with the error "Invalid credentials". I am able to use the same username and password to login via AD explorer.
Latest version (2.9) of ldap3 is being used, python version is 3.7 and OS is windows server 2012 R2. Tried the same code on ubuntu as well with no luck.

tls = Tls(ca_certs_data=cert_file, validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1_2)
server = Server('xxxx.domain.com', use_ssl=True, get_info=ALL)
conn = Connection(server, user='domain\\user_id', password='xxxxxxx' ,authentication=NTLM)
conn.start_tls()
conn.bind()
print(conn.result)
if not conn.bind():
    print('error in bind', conn.result)
    sys.exit(3)

Error: {'result': 49, 'description': 'invalidCredentials', 'dn': '', 'message': '80090346: LdapErr: DSID-0C0906D2, comment: AcceptSecurityContext error, data 80090346, v3839\x00', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'}

**Comment by zorn96** [comment]
hi @py-prash ! this (I'm 99% certain) isn't an issue in the library - rather it has to do with a fundamental difference between the LDAP protocol and AD explorer

There's a lot of ways to represent a username, especially in AD
1. domain.com\username
2. username (only works for single-domain forests with no global catalog enabled I believe)
3. username@domain.com
4. CN=user-common-name,CN=Users,DC=domain,DC=com (or something similar)

so I think your issue is that you're using the first style. in my experience with AD and LDAP, I've never seen "domain.com\username" actually work for an LDAP bind, and have never seen an option to enable it in AD

could you try using the "username@domain.com" style? I believe that's the most common format of username that I've seen with NTLM and Kerberos, and LDAP-based applications that accept "domain.com\username" are almost always just converting it internally

if switching to username@domain.com style doesn't work, could you let me know if the result message changes? thanks in advance 😄

**Comment by zorn96** [comment]
added the docs label potentially pre-emptively, as if we add a "Things to know specific to Active Directory" section, this one would be good to include as well

**Comment by py-prash** [comment]
If I just give "username@domain.com", it errors out with "NTLM needs domain\username and a password".

**Comment by py-prash** [comment]
I am not very familiar with NTLM. To learn more about the process that occurs underneath, i have the extended log version enabled. And what confuses me is that when the code binds against a domain controller that still accepts NTLM v1, it works fine. But when I switch to a domain controller which accepts only NTLMv2, the bind fails. Pretty sure, I am missing some kind of a control parameter.

**Comment by zorn96** [comment]
sorry, I should have refreshed myself before replying. the backslash format is definitely correct, and `ldap3` handles it internally
```
                    # additional import for NTLM
                    from ..utils.ntlm import NtlmClient
                    domain_name, user_name = self.user.split('\\', 1)
                    ntlm_client = NtlmClient(user_name=user_name, domain=domain_name, password=self.password)
```

according to microsoft's docs on the matter, it will only send invalid credentials if the dc actually thinks it "invalid" in some way https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/8b9dbfb2-5b6a-497a-a533-7e709cb9a982?redirectedfrom=MSDN

could you turn on protocol level logging for the ldap3 library (though you may choose to further censor logs before posting) so we can see the difference in the SICILY responses from the 2 dcs?
we should log information about the negotiation which might help us to spot the difference
```
                        if 'NTLM' in sicily_packages:  # NTLM available on server
                            request = bind_operation(self.version, 'SICILY_NEGOTIATE_NTLM', ntlm_client)
                            if log_enabled(PROTOCOL):
                                log(PROTOCOL, 'NTLM SICILY NEGOTIATE request sent via <%s>', self)
                            response = self.post_send_single_response(self.send('bindRequest', request, controls))
                            if not self.strategy.sync:
                                _, result = self.get_response(response)
                            else:
                                if log_enabled(PROTOCOL):
                                    log(PROTOCOL, 'NTLM SICILY NEGOTIATE response <%s> received via <%s>', response[0],
                                        self)
                                result = response[0]
```

**Comment by py-prash** [comment]
It seems like with the upgraded domain controllers, channel binding token is a necessity. When CBT signing is turned off from domain controller, code works fine . But when the signing is required, the code fails. 
Any thoughts on how this can be fixed?

**Comment by zorn96** [comment]
ah ok, yes that makes sense. you mention channel signing, so I'm assuming you mean channel bind tokens rather than LDAP signing. the reason I assume this is because any LDAP signing policies should also be satisfied by the use of LDAPS or StartTLS, which it looks like you're using

the ldap3 library currently supports channel bind tokens with kerberos, but not with NTLM. let me look to see how difficult it would be to add it for NTLM. I haven't used NTLM as much, so I'll need to see what the negotiation looks like

**Comment by py-prash** [comment]
yes, it is channel binding tokens. Looks like MS is enabling it by default now.

**Comment by zorn96** [comment]
yup. that was a late 2020 update from them. for both ldap signing and channel binding tokens "undefined" went from "None" to "Required" in the policy

there's a few options here though to mitigate this in the meanwhile:

1. create a new group and group policy object in AD. put your LDAP accounts that will be used with ldap3 in the group. change the channel bind token policy for only that group to be "Negotiate" or "None" instead of "Required". move things out of the group once the library is capable of using CBTs with NTLM
2. change the channel bind token policy in the domain globally to "Negotiate" instead of "Required" and turn on audit events around connections with no CBTs. this will let your LDAP application work while the library doesn't support CBTs with NTLM, and let you use audit events to confirm that all clients have upgraded once the library does support it
3. switch to kerberos. kerberos is generally more secure than ntlm, and the library supports kerberos with CBTs. this is a lot of work though, and I don't seriously recommend it unless your domain already is configured for kerberos

**Comment by py-prash** [comment]
Thank You @zorn96 !
Our domain is configured to use kerberos. With ldap3, when using kerberos it needs the MIT kerberos to be installed and configured which I am not sure how to do. Instead, I switched over to use winkerberos but that's also not working.
I can float the option 1 and see if that's an acceptable solution.

**Comment by zorn96** [comment]
ah are you running on windows machines? that makes sense then
windows kerberos libraries are, and have always been, slightly different from posix kerberos libraries (which use MIT kerberos like you mention)

there's actually an issue I opened a while back to make ldap3 work with the native windows kerberos https://github.com/cannatag/ldap3/issues/908
but I haven't gotten around to it yet. and even once that's done, there's still potentially configuration needed outside of the ldap3 python script to get the system kerberos libraries ready (unless your machines are joined to the domain in which case I think it'd just work with native windows kerberos)

I'm not sure whether it'll be more work to get CBTs working for NTLM or to get native Kerberos working for windows machines; but I'll make sure to come back and update you when I get a chance to dig deeper on them 😄

**Comment by zorn96** [comment]
PR is out for native windows kerberos support, which includes CBTs
https://github.com/cannatag/ldap3/pull/928

will look at NTLM soon

**Comment by py-prash** [comment]
@zorn96 is there a way we can pass raw creds when doing kerberos auth? I am trying to use a service account to perform the ldap bind. It looks like the tickets need to be pre-generated? I used the kerberos.py version from your branch.

**Comment by zorn96** [comment]
hi @py-prash ! if you've looked at kerberos.py, you likely noticed that the implementation just builds on the python `gssapi` library. this is also mentioned in the docs
here's the docs for the python gssapi library - https://pypi.org/project/gssapi/

my recent change would add support for using `winkerberos` on windows instead of `gssapi`

to my knowledge, `gssapi` doesn't support using a username and password to authenticate. but you can use the username and password to generate a keytab and then pass location information about it with `cred_store` to gssapi, or passing base credential bytes in the sasl arguments for `gssapi` to use to authenticate (I haven't done this a ton so I'm fuzzy on the details)

but `winkerberos` on windows 100% requires that the client TGT already exist before negotiation, and there will be checks around that in my current change.

there's an algorithm for generating kerberos credentials from a username/password based on your encryption type and domain info.
you can potentially also shell out and run `kinit` (or equivalent) on your machine using the credentials you have.

**Comment by py-prash** [comment]
@zorn96 The branch hasn't been merged yet. Do you have an ETA on when the branch would be merged? I have been using the kerberos.py from the add-windows-kerberos-support and has been working well for me.

**Comment by zorn96** [comment]
hi @py-prash ! sorry for the long delay. I was getting things set up in azure to actually test my changes and it took a while.
you should be able to use the dev branch now in order to get the functionality. not super sure when the next package version will be released
