### ISSUE TITLE
NTLM works but default authentication scheme returns invalidCredentials

### ISSUE THREAD

**Issue by khteh** [cannatag/ldap3#929]
I am using python 3.6.12 with ldap3 library and Active Directory. This is my code snippet:
```
    #user = f'cn={ldap_username},OU=User-Accounts,{root_dn}' # Failed with invalidCredentials
    user = f'{ldap_username}' # Success
    print(user)
    server = Server(ldap_server, get_info=ALL)
    connection = Connection(server, user=user, password=ldap_password, authentication=NTLM)
    if not connection.bind():
        print(f" *** Cannot bind to ldap server! {connection.last_error}, result: {connection.result}")
        l_success_msg = f' ** Failed Authentication: {connection.last_error}'
    else:
        print(f" *** Successful bind to ldap server")
        l_success_msg = 'Success'
```
```
cn=username,OU=User-Accounts,DC=domain,DC=com
```
```
{'result': 49, 'description': 'invalidCredentials', 'dn': '', 'message': '80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 52e, v2580\x00', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'}
```
What's wrong with the simple authentication scheme?

**Comment by zorn96** [comment]
hi @khteh ! the issue is that NTLM isn't actually a native form of LDAP authentication. this is actually called out in the docs for the package - https://ldap3.readthedocs.io/en/latest/bind.html#ntlm

NTLM doesn't support using LDAP distinguished names. instead, it expects user principals (`sAMAccountName`, also sometimes called a user logon name) and domain information.
in _many_ cases, but not all, a user's common name matches their sAMAccountName, which is why your code works with NLTM. for truly robust code, you'd need make sure that what you have is their sAMAccountName

if you provide the username alone, the library will attempt to get domain information and populate in (`domain.com` in this case). you can also provide it yourself by giving the username in the `domain.com\username` format

let me know if that makes sense :)

**Comment by khteh** [comment]
Hi @zorn96 My question was actually why wouldn't the native form of auth, the default authentication without passing the authentication parameter value, work in my case? The same credentials pass the NTLM authentication. What do I miss?

**Comment by zorn96** [comment]
ah - so you're wondering why SIMPLE LDAP binds don't work?
some domains disable SIMPLE binds entirely, and require Kerberos/NTLM/etc., as SIMPLE binds can be considered less secure.

if you're seeing the DN work for a SIMPLE bind, but the username isn't, then that relates to how your domain is configured. according the RFC, allowable fields for user are entirely up to the domain in terms of what it's capable of mapping to unique user entires. some domains only accept DNs (`CN=something,OU=something,...`), some accept DNs and UPNs (`user@domain`), and others allow DNs, UPNs, and short usernames (`user`). it depends on how your domain is setup

in your case though, if SIMPLE bind isn't working at all for both DNs and usernames, and you're sure that the DN is correct, then it's likely that the domain is simply disallowing that form of authentication entirely

**Comment by khteh** [comment]
None of them work in my case except NTLM. 

Another question. Does the LDAP3 package provide any mechanism to validate authenticated API requests? How does it track if a user is logged in and how to log a user out? Thanks.

**Comment by zorn96** [comment]
hi @khteh - there's an UNBIND operation with a corresponding unbind() function in the library.
connection objects have a _bound_ member which is boolean and can be checked to determine if the connection was bound. however, that's our local knowledge of whether we're bound or not - some servers will terminate idle connections in which case we won't know until another operation is tried and an error is thrown saying the connection was reset by the peer
