### ISSUE TITLE
modifyPassword

### ISSUE THREAD

**Issue by ilovetacos** [cannatag/ldap3#974]
I was trying to use 
```
 extend.standard.modify_password(
        user,
        old_password,
        new_password,
        hash_algorithm=None,
        salt=None
    )
```
with an OpenLDAP Server v2.4.40. As soon as I used salt, the verification of the password with Apache Directory Studio did not work anymore. In `ldap3/utils/hashed.py` I intercepted the password. It was correct (in my case, I used the password `123456` and I got the string `{ssha}r2xa++/OES+d+Llhmrz7ea1nFcygy/4R`. However, in ADS I found `{SSHA}FY5Xmctlvh3eaiqiNpTvvS5Io7wa+nos`, which is the hash of the first string. The verification of the password, obviously, fails. 

So I came up with:
```
def ldap_pass(password):
    salt = os.urandom(4)
    h = hashlib.sha1(bytes(password, encoding='utf-8') + salt)
    b64digest = base64.b64encode(h.digest() + salt)
    byte_res = b"".join([bytes(i, encoding='utf-8') for i in ('{SSHA}', str(b64digest, 'utf-8'))])
    return str(byte_res, 'utf-8')
```
and do a MODIFY_ADD or MODIFY_REPLACE, depending on the use case. I don't know if I was doing something wrong or if maybe my LDAP version ist not compatible...  Maybe this helps somebody.

**Comment by grawity** [comment]
The "modify password" exop isn't the same as a literal modify. It expects the new password to be provided in _plain text_, and the server takes care of hashing it into whatever format it wants and storing it into whatever attribute it wants. (In other words, the whole purpose of this exop is to abstract away these details so that the client would not _need_ to care about hashing.)

**Comment by ilovetacos** [comment]
Thank you. I will leave it as is for now, because... never touch a running system -.-
