### ISSUE TITLE
Ldap3 authenticate using Kerberos with credentials

### ISSUE THREAD

**Issue by reach4bawer** [cannatag/ldap3#978]
I am using ldap3 to query Active Directory. My goal is connect to the active directory by authenticating via Kerberos. I wanted to provide the username and password to generate the kerberos ticket. I have the following code -

```
import ldap3
from pprint import pprint
import configparser
import ssl

config = configparser.ConfigParser()

config.read('config.ini')
LDAP_DOMAIN_URI = config['Domain']['Domain'] # This is url without ldap:// or ldaps://
LDAP_DOMAIN_BASE = config['Domain']['base'] # Base of the domain for search
username = config['Credentials_srv']['username']+"@domain.com" # Username with the domain
password = config['Credentials_srv']['password']
CACERT_FILE = "./cacerts.pem"
tls_configuration = ldap3.Tls(validate=ssl.CERT_NONE,
                              version=ssl.PROTOCOL_TLSv1_2, ca_certs_file = CACERT_FILE)
server = ldap3.Server(LDAP_DOMAIN_URI,port=636 , use_ssl=True, allowed_referral_hosts=[("*", True)], tls=tls_configuration, get_info=ldap3.ALL, mode=ldap3.IP_V4_ONLY)

conn = ldap3.Connection(server, client_strategy=ldap3.SAFE_SYNC, auto_referrals=True, auto_bind=True, authentication=ldap3.SASL, sasl_mechanism=ldap3.KERBEROS, user = username, password = password, raise_exceptions=False)

query = '(&(objectClass=group)(SamAccountName=Test Group))'

status, result, response, referrals = conn.search(LDAP_DOMAIN_BASE, query ,attributes=['*']) 
```
I might be doing something wrong as I am getting when I try this on my windows machine -

```
status = winkerberos.authGSSClientStep(ctx, base64.b64encode(in_token).decode('utf-8'),
winkerberos.GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable
```
I tried this on a mac and I get -

```
File "gssapi/raw/creds.pyx", line 161, in gssapi.raw.creds.acquire_cred
gssapi.raw.exceptions.MissingCredentialsError: Major (458752):  No credentials were supplied, or the credentials were unavailable or inaccessible., Minor (0): unknown mech-code 0 for mech unknown
```
I have the virtual environment in both with -

```
gssapi==1.6.14
ldap3==2.9.1
winkerberos==0.8.0 (only on windows)
```
What can I do differently be able to successfully bind to the AD?

**Comment by zorn96** [comment]
Hi @reach4bawer ! There’s a few things here.

When i added winkerberos support, I actually assumed that people would use one or the other, not both 😬 so that’s likely the source of your problems. 

when gssapi is installed, we’ll always use  that one, because that was supported first and the new 2.9.0+ needed to provide a non-disruptive upgrade for people already using it.

so on windows you want to make sure that you only have winkerberos to avoid weird behaviors.

on macOS, afaik, gssapi does not support initiating with a username and password. So you’d need to shell out and kinit to make that work.

this brings me to the next main point: it looks like your hostname is bad.
You’re using the domain name as the server address. However, I can tell you from experience that the actual kerberos names of the domain controllers are different, which is why you see the error you’re seeing on Windows.
The proper kerberos names for ldap servers in AD are stored in special SRV records in dns.

I’m on my phone at the moment, but I’ve actually been working on another library that wraps around ldap3 for some AD-specific stuff like this, which might help you out. I’ll link it once I’m on a computer. It’s not done yet, but the logic you’d want is all there so you can copy+paste it

**Comment by reach4bawer** [comment]
Hi @zorn96 Thank you for your quick response. This is helpful. 

I used gssapi on mac because that was the only supported method as winkerberos was is not supported. As gssapi is the common for both the windows and mac os, I was thinking of using that instead of winkerberos but I have not done this in the past so please correct me here if one is preferred over the other.

For `kinit`,  how would I pass the ticket after obtaining it via command `kinit ad@domain.COM username password` or via the example in https://uit.stanford.edu/service/ess/mac/docs/kerberos_macOS?

For the hostname are you talking about using one of the hostname retuned from `nslookup -type=srv _kerberos._tcp.<CLIENT_DOMAIN>`? 

For the other library if you have something in works please let me know that would be helpful :)

**Comment by zorn96** [comment]
if `gssapi` works for you on windows then you should be fine to keep using it.
if you create a connection with `ldap3` and use kerberos as the encryption type without passing any specific `sasl_credentials` parameters, then `gssapi` will look for credentials in the default location for a posix operating system, which is also where `kinit` will write them (unless your system configuration dictates otherwise)

to communicate with an LDAP server using kerberos, you actually want the hostname that has an LDAP service record. so that's `nslookup -type=SRV _ldap._tcp.dc._msdcs.<DOMAIN>`

the library I've been working on to simplify AD-specific stuff (not yet actually available as a python package) is https://github.com/zorn96/ms_active_directory

specifically, https://github.com/zorn96/ms_active_directory/blob/main/environment/discovery/discovery_utils.py and https://github.com/zorn96/ms_active_directory/blob/main/environment/discovery/discovery_constants.py contain logic for discovering LDAP controllers within an AD domain, and sorting them by reachability and RTT after accounting for whether or not they support TLS.
so hopefully some of the logic there is helpful, even though it's not yet a package you can easily pip install

**Comment by reach4bawer** [comment]
Thank you for sharing the links. I took the package you shared and incorporated in the script on my windows machine. Removed GSSAPI just to get something working. I kept winkerberos, modified the script to the following - 

```
import ldap3
from pprint import pprint
import configparser
import ssl

config = configparser.ConfigParser()
ldap_servers = discovery_utils.discover_ldap_domain_controllers_in_domain(domain = 'domain.com', secure=True)
config.read('config.ini')
LDAP_DOMAIN_URI = config['Domain']['Domain'] # This is url without ldap:// or ldaps://
LDAP_DOMAIN_BASE = config['Domain']['base'] # Base of the domain for search
username = config['Credentials_srv']['username']+"@domain.com" # Username with the domain
password = config['Credentials_srv']['password']
CACERT_FILE = "./cacerts.pem"
tls_configuration = ldap3.Tls(validate=ssl.CERT_NONE,
                              version=ssl.PROTOCOL_TLSv1_2, ca_certs_file = CACERT_FILE)


server_list = []
for LDAPURL in ldap_servers:
    server_list.append(ldap3.Server(LDAPURL.split(':')[0],port=636 , use_ssl=True,allowed_referral_hosts=[("*", True)], tls=tls_configuration,get_info=ldap3.ALL, mode=ldap3.IP_V4_ONLY))

conn = ldap3.Connection(server_list, client_strategy=ldap3.SAFE_SYNC, auto_referrals=True, auto_bind=True, authentication=ldap3.SASL, sasl_mechanism=ldap3.KERBEROS, user = username, password = password, raise_exceptions=False)

query = '(&(objectClass=group)(SamAccountName=Test Group))'

status, result, response, referrals = conn.search(LDAP_DOMAIN_BASE, query ,attributes=['*']) 
```

The script never completes execution and although I get no errors but I do not get any outputs after 5-10 mins of execution. There are quite a few servers that come up in the list, while I tried the kerberos discovery   `discover_kdc_domain_controllers_in_domain` it didn't list anything while` nslookup -type=srv _kerberos._tcp.dc._msdcs.<domain.com>` does list quite a few.

**Comment by zorn96** [comment]
@reach4bawer maybe try printing the URIs you're using? or specifying a server limit?

it looks like there might be a bug in
```
server_list = []
for LDAPURL in ldap_servers:
    server_list.append(ldap3.Server(LDAPURL.split(':')[0],port=636 , use_ssl=True,allowed_referral_hosts=[("*", True)], tls=tls_configuration,get_info=ldap3.ALL, mode=ldap3.IP_V4_ONLY))
```
the elements in `ldap_servers`, assuming you didn't modify `discover_ldap_domain_controllers_in_domain`, are of the format `ldap://server-uri:port` so when you do `LDAPURL.split(':')[0]`, I think you're just getting `ldap`

the reason your script is hanging _might_ be because your domain has a large number of servers, with some of them being very far away. that's actually why I added the server limit functionality, since there's a lot of workflows where you'd rather fail then wait too long on finding an available server.

**Comment by reach4bawer** [comment]
I had modified the list of the `ldap_servers` to only contain the hostname and the port (separated by ':'). When I just test with the first server I get - `ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: [WinError 10054] An existing connection was forcibly closed by the remote host`

On following your solution and modifying the code to do manual bind and using `discover_ldap_domain_controllers_in_domain` out of the box here is the code -

```
import ldap3
from pprint import pprint
import configparser
import ssl
from environment.discovery import discovery_utils

config = configparser.ConfigParser()

config.read('config.ini')
LDAP_DOMAIN_URI = config['Domain']['Domain'] # This is url without ldap:// or ldaps://
LDAP_DOMAIN_BASE = config['Domain']['base'] # Base of the domain for search
username = config['Credentials_srv']['username']+"@domain.com" # Username with the domain
password = config['Credentials_srv']['password']
CACERT_FILE = "./cacerts.pem"

ldap_servers = discovery_utils.discover_ldap_domain_controllers_in_domain(domain = 'domain.com', secure=True)

tls_configuration = ldap3.Tls(validate=ssl.CERT_NONE,
                              version=ssl.PROTOCOL_TLSv1_2, ca_certs_file = CACERT_FILE)
server_list = []
for LDAPURL in ldap_servers:
    server_list.append(ldap3.Server(LDAPURL.split('://')[1].split(':')[0], port=389 , use_ssl=False, allowed_referral_hosts=[("*", True)], tls=tls_configuration, get_info=ldap3.ALL, mode=ldap3.IP_V4_ONLY)) 
pprint(server_list)

conn = ldap3.Connection(server_list[0], client_strategy=ldap3.SAFE_SYNC, auto_referrals=True, auto_bind=False, authentication=ldap3.SASL, sasl_mechanism=ldap3.KERBEROS, user = username, password = password, raise_exceptions=False)
conn.start_tls()
conn.bind()
status, result, response, referrals = conn.search(LDAPBASE, '(&(objectClass=group)(SamAccountName=Test Group))', attributes=['*'])
pprint(response[0].get('attributes').get('member'))
```

When I did this it actually was able to connect on my windows machine. Surprisingly, I used this domain which didn't have any of the severs that had LDAPS enabled. The discovery module still gave me the list of ldap sever with port 389. Doing a manual bind worked. 

Is there a way to do this with autobind, as if I enable autobind while declaring conn I get -

`TypeError: Expected a channel bindings object`

**Comment by zorn96** [comment]
@reach4bawer thanks for the details. are you sure your domain is enabled for LDAPS? Could there be a policy or firewall in the way?

anyway, there is an auto bind option that should work for you if this is working. I forget the exact name offhabd, but it’s in the docs, it’s something like AUTO_BIND_START_TLS_BEFORE_BIND.
and it’ll do what you’re doing here, but at the time of instantiating the connection.

i personally prefer to open manually, then start tls, then bind, especially with a server pool, since it gives better flexibility for debugging which server you connected to and such in case of errors.

also, totally unrelated to your current issue, with AD I would recommend using the SAFE_RESTARTABLE strategy over SAFE_SYNC unless this is a one-off script to be run manually.
AD domains will idle timeout connections by default, and so a restartable approach will give you the most seamless “it just works” experience with any program that potentially needs a longer lived connection

**Comment by reach4bawer** [comment]
@zorn96  It might be firewall that is causing the problem. 

I found the [document](https://ldap3.readthedocs.io/en/latest/connection.html?highlight=AUTO_BIND_TLS_BEFORE_BIND#connection) thanks you for sharing and changed the code to SAFE_RESTARTABLE. 

Would you happen to know how I can pass the credentials for the kerberos instead of the script reading my default credentials? As even after passing the credentials as sasl_credentials it does not resolve. I tried -

`conn = ldap3.Connection(server_list, client_strategy=ldap3.SAFE_RESTARTABLE, auto_referrals=True,auto_bind=ldap3.AUTO_BIND_TLS_BEFORE_BIND, authentication=ldap3.SASL, sasl_mechanism=ldap3.KERBEROS, sasl_credentials=(ldap3.ReverseDnsSetting. OPTIONAL_RESOLVE_ALL_ADDRESSES, username, password), raise_exceptions=False)`

It gives me -

`ldap3.core.exceptions.LDAPPackageUnavailableError: The winkerberos package does not support specifying raw  credentialsto initiate GSSAPI Kerberos communication. A ticket granting ticket must have already been obtained for the user before beginning a SASL bind.`

**Comment by zorn96** [comment]
@reach4bawer as far as I'm aware, `winkerberos` doesn't support using a username and password to generate a kerberos ticket. so if you want to use `winkerberos`, you need to generate a ticket externally.
if you're on windows then that means invoking `klist` manually as needed if your computer doesn't belong to the domain https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/klist
if it does belong to the domain, then you should already have a TGT from your login and not need to do anything special

**Comment by zorn96** [comment]
hi @reach4bawer ! are we ok to close this? it seems like at this point, the issues are external to the ldap3 library

**Comment by reach4bawer** [comment]
@zorn96 yes we can close this. For someone looking to generate the kerberos ticket from the python script please you the following -

```
from subprocess import Popen, PIPE, run
userid = 'username'
realm = 'myrealm.com'
password = 'password'
kinit = '/usr/bin/kinit' # if you are on windows then you can use kinit to call the kinit replace with "kinit"
kinit_run = run(f'echo "{password}" | {kinit} {userid}@{realm}',shell=True, check=True, 
               stdout=PIPE, stderr=PIPE, text=True)
```
