### ISSUE TITLE
Most efficient way to login

### ISSUE THREAD

**Issue by abdiels** [cannatag/ldap3#998]
Hello,

    I am using LDAP3 for authentication.  Currently, I am having to do a search with the user id provided to get the exact dn user name to then bind using that dn and password.  Is there a better way to do that?  Like doing a search and bind with password directly?  Or pass a wildcard in the user name?  Or any other suggestions to avoid connecting twice.  Any pointers would be greatly appreciated.  My goal is to speed up this process as much as possible.

Here is what I am doing:

    server = Server(server_uri, server_port, use_ssl=True, get_info=ALL)
    conn = Connection(server)
    if not conn.bind():
        logger.error('error in bind', conn.result)
    else:
        conn.search(search_base, search_filter, attributes=attrs)
        if len(conn.entries) >= 1:
            if len(conn.entries) > 1:
                logger.error("More than one user with login: " + user_name)
            else:
                user_info = conn.entries[0]
                logger.debug("User entry returned by LDAP: " + str(user))
        else:
            logger.error("User Not found: " + user_name)

    if user_info is not None:
        conn = Connection(server, user_info.entry_dn, user_password, check_names=True,
                          lazy=False,
                          client_strategy=SYNC,
                          raise_exceptions=False, authentication=SIMPLE)
        conn.bind()

Thank you,

Abdiel

**Comment by abdiels** [comment]
I found this issue:  https://github.com/cannatag/ldap3/issues/534#issue-322738121 and I updated my code to use get_info=None on server and check_names=False on the connection and that has dramatically improved my speed.  It used to take 5-6 seconds, not I am down to less than a second!!  I am not closing the issue in case you have additional suggestions; otherwise, this can be closed.

**Comment by zorn96** [comment]
@abdiels depending on the configuration of your LDAP server, you may be able to bind using a username instead of a DN.
for example, with AD you can bind with `sAMAccountName@domain` by default, instead of the dn `CN=whatever,....`. and if you configure your domain properly you can bind with `sAMAccountName` alone.

some configurations of OpenLDAP also support binding with `uid` alone, and oracle unified directory supports just `CN=name` without the rest of the path for some users.

according to the LDAP spec, this is entirely up to the server, so you may or may not be able to tell what options exist programmatically. but if you test with your server one of those options might work :)
